<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<?xml-stylesheet ekr_test ?>
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5" body_secondary_ratio="0.5">
	<global_window_position top="50" left="50" height="500" width="700"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="amd.20150913232631.1"><vh>@settings</vh>
<v t="amd.20150913232631.2"><vh>@data qt-gui-plugin-style-sheet</vh></v>
<v t="amd.20150913232631.3"><vh>@string initial_split_orientation = horizontal</vh></v>
</v>
<v t="amd.20150919102739.1"><vh>專案架構</vh>
<v t="amd.20150919113520.1"><vh>@edit .gitignore</vh></v>
<v t="amd.20151007224830.1"><vh>Jupyter 安裝與執行</vh></v>
<v t="amd.20150919103357.1"><vh>pelican 設定</vh></v>
</v>
<v t="amd.20150919113957.1" a="E"><vh>以下為 pelican 文章</vh>
<v t="amd.20151021120245.1"><vh>@button admin pelican</vh></v>
<v t="amd.20150919124128.1"><vh>@button user pelican</vh></v>
<v t="amd.20150919114010.1" a="E"><vh>@path pelican</vh>
<v t="amd.20151006130205.1"><vh>@edit publishconf.py</vh></v>
<v t="amd.20151006113136.1" a="E"><vh>@path content</vh>
<v t="amd.20150919114035.1"><vh>@edit 2015cphww1.md</vh></v>
<v t="leo.20151115135557.1"><vh>@edit 2015cphww2.md</vh></v>
<v t="leo.20151115220721.1"><vh>@edit 2015cphww3.md</vh></v>
<v t="leo.20151115220851.1"><vh>@edit 2015cphww4.md</vh></v>
<v t="leo.20151115220901.1"><vh>@edit 2015cphww5.md</vh></v>
<v t="leo.20151115220908.1"><vh>@edit 2015cphww6.md</vh></v>
<v t="leo.20151115220917.1"><vh>@edit 2015cphww7.md</vh></v>
<v t="leo.20151115220926.1"><vh>@edit 2015cphww8.md</vh></v>
<v t="leo.20151115220945.1"><vh>@edit 2015cphww9.md</vh></v>
<v t="leo.20151119131311.1"><vh>@edit 2015cphww10.md</vh></v>
<v t="leo.20151201231236.1"><vh>@edit 2015cphww11.md</vh></v>
<v t="leo.20151201232631.1"><vh>@edit 2015cphww12.md</vh></v>
<v t="leo.20151201233430.1"><vh>@edit 2015cphww13.md</vh></v>
<v t="leo.20151201233442.1"><vh>@edit 2015cphww14.md</vh></v>
<v t="leo.20151201233448.1"><vh>@edit 2015cphww15.md</vh></v>
<v t="leo.20151201233454.1"><vh>@edit 2015cphww16.md</vh></v>
<v t="leo.20151201233501.1"><vh>@edit 2015cphww17.md</vh></v>
<v t="amd.20150920000911.1"><vh>@edit 2015cpnote1.md</vh></v>
</v>
</v>
</v>
<v t="amd.20150919120205.1" a="E"><vh>以下為 reveal 投影片</vh>
<v t="amd.20150915155634.1"><vh>@clean cadpaw1.html</vh>
<v t="amd.20150915155634.2" a="E"><vh>html 標註</vh>
<v t="amd.20150915155634.3" a="E"><vh>head</vh>
<v t="amd.20150915155634.4"><vh>title - 標題</vh></v>
<v t="amd.20150915155634.5"><vh>meta - 說明</vh></v>
<v t="amd.20150915155634.7"><vh>script - css 與 pdf 列印</vh></v>
</v>
<v t="amd.20150915155634.8" a="E"><vh>body</vh>
<v t="amd.20150915155634.9" a="E"><vh>div - reveal</vh>
<v t="amd.20150915155634.10" a="E"><vh>div - slides</vh>
<v t="amd.20150915155634.11"><vh>h1 - 課程說明</vh></v>
<v t="amd.20150915172241.1"><vh>h1 - 開放自評規劃</vh></v>
<v t="amd.20150915155634.12"><vh>h2 - 實體輔助工具</vh></v>
<v t="amd.20150915155634.13"><vh>h2 - 垂直有下屬頁</vh>
<v t="amd.20150915155634.14"><vh>h2</vh></v>
<v t="amd.20150915155634.15"><vh>h2</vh></v>
<v t="amd.20150915155634.16"><vh>h2</vh></v>
</v>
<v t="amd.20150915173703.1"><vh>h2 - 內含程式碼頁面</vh>
<v t="amd.20150915173703.2" a="E"><vh>pre</vh>
<v t="amd.20150915173703.3"><vh>code</vh></v>
</v>
<v t="amd.20150915173703.4"><vh>p</vh></v>
</v>
<v t="amd.20150915155634.17"><vh>h2</vh></v>
<v t="amd.20150915204710.1"><vh>內嵌 Vimeo 影片</vh></v>
<v t="amd.20150915155634.18"><vh>h2</vh></v>
<v t="amd.20150915155634.19"><vh>h2</vh></v>
<v t="amd.20150915155634.20"><vh>markdown 頁面</vh></v>
<v t="amd.20150915155634.21" a="E"><vh>h2</vh>
<v t="amd.20150915160450.1"><vh>Fragement 主頁面</vh></v>
<v t="amd.20150915155634.28" a="E"><vh>下屬頁面</vh>
<v t="amd.20150915161424.1"><vh>h2</vh></v>
<v t="amd.20150915155634.29"><vh>p</vh></v>
<v t="amd.20150915155634.30"><vh>p</vh></v>
<v t="amd.20150915155634.31"><vh>p</vh></v>
<v t="amd.20150915155634.32"><vh>p</vh></v>
<v t="amd.20150915155634.33"><vh>p</vh></v>
<v t="amd.20150915155634.34"><vh>p</vh></v>
<v t="amd.20150915155634.35"><vh>p</vh></v>
</v>
</v>
<v t="amd.20150915155634.36"><vh>h2</vh></v>
<v t="amd.20150915155634.37"><vh>p</vh>
<v t="amd.20150915155634.38"><vh>a</vh></v>
<v t="amd.20150915155634.39"><vh>a</vh></v>
<v t="amd.20150915155634.40"><vh>a</vh></v>
<v t="amd.20150915155634.41"><vh>a</vh></v>
<v t="amd.20150915155634.42"><vh>a</vh></v>
<v t="amd.20150915155634.43"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.44"><vh>h2 - 更換主題</vh></v>
<v t="amd.20150915155634.45" a="E"><vh>p</vh>
<v t="amd.20150915155634.46"><vh>a</vh></v>
<v t="amd.20150915155634.47"><vh>a</vh></v>
<v t="amd.20150915155634.48"><vh>a</vh></v>
<v t="amd.20150915155634.49"><vh>a</vh></v>
<v t="amd.20150915155634.50"><vh>a</vh></v>
<v t="amd.20150915155634.51"><vh>a</vh></v>
<v t="amd.20150915155634.52"><vh>a</vh></v>
<v t="amd.20150915155634.53"><vh>a</vh></v>
<v t="amd.20150915155634.54"><vh>a</vh></v>
<v t="amd.20150915155634.55"><vh>a</vh></v>
<v t="amd.20150915155634.56"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.57"><vh>h2</vh></v>
<v t="amd.20150915155634.58"><vh>p</vh>
<v t="amd.20150915155634.59"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.60"><vh>a</vh></v>
<v t="amd.20150915155634.61"><vh>h2</vh></v>
<v t="amd.20150915155634.62" a="E"><vh>pre</vh>
<v t="amd.20150915155634.63"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.64"><vh>h2 - 背景填圖頁面</vh></v>
<v t="amd.20150915155634.65" a="E"><vh>pre</vh>
<v t="amd.20150915155634.66"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.67" a="E"><vh>div</vh>
<v t="amd.20150915155634.68"><vh>h2</vh></v>
<v t="amd.20150915155634.69"><vh>pre</vh>
<v t="amd.20150915155634.70"><vh>code</vh></v>
</v>
</v>
<v t="amd.20150915155634.71"><vh>h2</vh></v>
<v t="amd.20150915155634.72"><vh>h2</vh></v>
<v t="amd.20150915155634.73"><vh>p</vh></v>
<v t="amd.20150915155634.74"><vh>pre</vh>
<v t="amd.20150915155634.75"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.76"><vh>h2 - 背景轉換</vh></v>
<v t="amd.20150915155634.77"><vh>p</vh></v>
<v t="amd.20150915155634.78" a="E"><vh>pre</vh>
<v t="amd.20150915155634.79"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.80" a="E"><vh>h2 - 內含程式碼頁面</vh>
<v t="amd.20150915155634.81" a="E"><vh>pre</vh>
<v t="amd.20150915155634.82"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.83"><vh>p</vh></v>
</v>
<v t="amd.20150915155634.85"><vh>h2</vh></v>
<v t="amd.20150915155634.86" a="E"><vh>ul</vh>
<v t="amd.20150915155634.87"><vh>li</vh></v>
<v t="amd.20150915155634.88"><vh>li</vh></v>
<v t="amd.20150915155634.89"><vh>li</vh></v>
<v t="amd.20150915155634.90"><vh>li</vh></v>
</v>
<v t="amd.20150915155634.91"><vh>h2</vh></v>
<v t="amd.20150915155634.92"><vh>ol</vh>
<v t="amd.20150915155634.93"><vh>li</vh></v>
<v t="amd.20150915155634.94"><vh>li</vh></v>
<v t="amd.20150915155634.95"><vh>li</vh></v>
</v>
<v t="amd.20150915155634.96"><vh>h2 - 表格頁面</vh></v>
<v t="amd.20150915155634.97" a="E"><vh>table</vh>
<v t="amd.20150915155634.98"><vh>thead</vh>
<v t="amd.20150915155634.99"><vh>tr</vh>
<v t="amd.20150915155634.100"><vh>th</vh></v>
<v t="amd.20150915155634.101"><vh>th</vh></v>
<v t="amd.20150915155634.102"><vh>th</vh></v>
</v>
</v>
<v t="amd.20150915155634.103"><vh>tbody</vh>
<v t="amd.20150915155634.104"><vh>tr</vh>
<v t="amd.20150915155634.105"><vh>td</vh></v>
<v t="amd.20150915155634.106"><vh>td</vh></v>
<v t="amd.20150915155634.107"><vh>td</vh></v>
</v>
<v t="amd.20150915155634.108"><vh>tr</vh>
<v t="amd.20150915155634.109"><vh>td</vh></v>
<v t="amd.20150915155634.110"><vh>td</vh></v>
<v t="amd.20150915155634.111"><vh>td</vh></v>
</v>
<v t="amd.20150915155634.112"><vh>tr</vh>
<v t="amd.20150915155634.113"><vh>td</vh></v>
<v t="amd.20150915155634.114"><vh>td</vh></v>
<v t="amd.20150915155634.115"><vh>td</vh></v>
</v>
</v>
</v>
<v t="amd.20150915155634.116"><vh>h2</vh></v>
<v t="amd.20150915155634.117"><vh>p</vh>
<v t="amd.20150915155634.118"><vh>q</vh></v>
</v>
<v t="amd.20150915155634.119"><vh>blockquote</vh></v>
<v t="amd.20150915155634.120"><vh>h2</vh></v>
<v t="amd.20150915155634.121"><vh>p</vh>
<v t="amd.20150915155634.122"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.123"><vh>h2</vh></v>
<v t="amd.20150915155634.124" a="E"><vh>p</vh>
<v t="amd.20150915155634.125"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.126"><vh>p</vh>
<v t="amd.20150915155634.127"><vh>em</vh></v>
</v>
<v t="amd.20150915155634.128"><vh>h2</vh></v>
<v t="amd.20150915155634.129"><vh>p</vh>
<v t="amd.20150915155634.130"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.131"><vh>iframe</vh></v>
<v t="amd.20150915155634.132"><vh>h2</vh></v>
<v t="amd.20150915155634.133" a="E"><vh>p</vh>
<v t="amd.20150915155634.134"><vh>code</vh></v>
<v t="amd.20150915155634.135"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.136"><vh>h2</vh></v>
<v t="amd.20150915155634.137"><vh>p</vh>
<v t="amd.20150915155634.138"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.139"><vh>pre</vh>
<v t="amd.20150915155634.140"><vh>code</vh></v>
</v>
<v t="amd.20150915155634.141"><vh>h2 按下 b 或 . 可以 black 畫面</vh></v>
<v t="amd.20150915155634.142"><vh>p</vh></v>
<v t="amd.20150915155634.143" a="E"><vh>h2 unordered list 頁面</vh>
<v t="amd.20150915155634.148"><vh>li</vh>
<v t="amd.20150915155634.149"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.150"><vh>li</vh>
<v t="amd.20150915155634.151"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.152"><vh>li</vh>
<v t="amd.20150915155634.153"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.146"><vh>li</vh>
<v t="amd.20150915155634.147"><vh>a</vh></v>
</v>
<v t="amd.20150915155634.145"><vh>li</vh></v>
</v>
<v t="amd.20150915155634.154"><vh>結束單頁</vh></v>
</v>
</v>
<v t="amd.20150915155634.158"><vh>script</vh></v>
<v t="amd.20150915155634.159"><vh>script</vh></v>
<v t="amd.20150915155634.160"><vh>script</vh></v>
</v>
</v>
</v>
<v t="amd.20150913233943.1"><vh>@clean cadpbw1.html</vh>
<v t="amd.20150913233943.2" a="E"><vh>html</vh>
<v t="amd.20150913233943.3" a="E"><vh>head</vh>
<v t="amd.20150913233943.4"><vh>title</vh></v>
</v>
<v t="amd.20150913233943.5" a="E"><vh>body</vh>
<v t="amd.20150913233943.6" a="E"><vh>div</vh>
<v t="amd.20150913233943.7" a="E"><vh>div</vh>
<v t="amd.20150913234947.1"><vh>title page</vh>
<v t="amd.20150913235225.1"><vh>標題頁下的子頁</vh></v>
</v>
<v t="amd.20150913235034.1"><vh>本日要點</vh></v>
<v t="amd.20150914000138.1"><vh>Anaconda Python</vh></v>
<v t="amd.20150914000332.1" a="E"><vh>設計的表達方式</vh>
<v t="amd.20150914000332.2"><vh>協同模式下的網際雲端內容呈現</vh></v>
</v>
<v t="amd.20150913235123.1"><vh>結論</vh></v>
</v>
</v>
<v t="amd.20150913233943.81"><vh>script</vh></v>
<v t="amd.20150913233943.82"><vh>script</vh></v>
<v t="amd.20150913233943.83"><vh>script</vh></v>
</v>
</v>
</v>
<v t="ibm.20150918175403.1"><vh>@clean cpw1.html</vh>
<v t="ibm.20150918175403.2"><vh>檔案說明</vh></v>
<v t="ibm.20150918175403.3" a="E"><vh>html 標註</vh>
<v t="ibm.20150918175403.4" a="E"><vh>body 標註</vh>
<v t="ibm.20150918175403.5" a="E"><vh>div class="reveal"</vh>
<v t="ibm.20150918175403.6" a="E"><vh>div class="slides"</vh>
<v t="ibm.20150918175403.7"><vh>有關我的作業</vh></v>
<v t="ibm.20150918175403.8"><vh>課程規劃</vh></v>
<v t="ibm.20150918175403.9"><vh>作業規劃</vh></v>
<v t="ibm.20150918175711.1"><vh>Git 操作</vh></v>
<v t="ibm.20150918175951.1"><vh>Jupyter 操作</vh></v>
<v t="ibm.20150918181528.1"><vh>結論</vh></v>
</v>
</v>
<v t="ibm.20150918175403.10"><vh>script</vh></v>
</v>
</v>
</v>
<v t="amd.20150915211341.1"><vh>@clean simplest1.html</vh>
<v t="amd.20150917085040.1"><vh>檔案說明</vh></v>
<v t="amd.20150915211351.1" a="E"><vh>html 標註</vh>
<v t="amd.20150915211351.4" a="E"><vh>body 標註</vh>
<v t="amd.20150915211351.5" a="E"><vh>div class="reveal"</vh>
<v t="amd.20150915211351.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151115135311.1"><vh>首頁</vh></v>
<v t="amd.20150915211351.7"><vh>自我介紹</vh></v>
<v t="leo.20151115223816.1"><vh>課程內容</vh></v>
<v t="amd.20150915211351.9"><vh>作業任務</vh></v>
<v t="amd.20150915211351.12"><vh>作業成果</vh></v>
<v t="leo.20151115224848.1"><vh>心得與自評</vh></v>
</v>
</v>
<v t="amd.20150915211351.15"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151115232422.1"><vh>@clean simplest2.html</vh>
<v t="leo.20151115232422.2"><vh>檔案說明</vh></v>
<v t="leo.20151115232422.3" a="E"><vh>html 標註</vh>
<v t="leo.20151115232422.4" a="E"><vh>body 標註</vh>
<v t="leo.20151115232422.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151115232422.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151115232422.7"><vh>首頁</vh></v>
<v t="leo.20151115232422.8"><vh>自我介紹</vh></v>
<v t="leo.20151115232422.9"><vh>課程內容</vh></v>
<v t="leo.20151115232422.10"><vh>作業任務</vh></v>
<v t="leo.20151115232422.11"><vh>作業成果</vh></v>
<v t="leo.20151115232422.12"><vh>心得與自評</vh></v>
</v>
</v>
<v t="leo.20151115232422.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151115232433.1"><vh>@clean simplest3.html</vh>
<v t="leo.20151115232433.2"><vh>檔案說明</vh></v>
<v t="leo.20151115232433.3" a="E"><vh>html 標註</vh>
<v t="leo.20151115232433.4" a="E"><vh>body 標註</vh>
<v t="leo.20151115232433.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151115232433.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151115232433.7"><vh>首頁</vh></v>
<v t="leo.20151115232433.8"><vh>自我介紹</vh></v>
<v t="leo.20151115232433.9"><vh>課程內容</vh></v>
<v t="leo.20151115232433.10"><vh>作業任務</vh></v>
<v t="leo.20151115232433.11"><vh>作業成果</vh></v>
<v t="leo.20151115232433.12"><vh>心得與自評</vh></v>
</v>
</v>
<v t="leo.20151115232433.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151115232441.1"><vh>@clean simplest4.html</vh>
<v t="leo.20151115232441.2"><vh>檔案說明</vh></v>
<v t="leo.20151115232441.3" a="E"><vh>html 標註</vh>
<v t="leo.20151115232441.4" a="E"><vh>body 標註</vh>
<v t="leo.20151115232441.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151115232441.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151115232441.7"><vh>首頁</vh></v>
<v t="leo.20151115232441.8"><vh>自我介紹</vh></v>
<v t="leo.20151115232441.9"><vh>課程內容</vh></v>
<v t="leo.20151115232441.10"><vh>作業任務</vh></v>
<v t="leo.20151115232441.11"><vh>作業成果</vh></v>
<v t="leo.20151115232441.12"><vh>心得與自評</vh></v>
</v>
</v>
<v t="leo.20151115232441.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151115232449.1"><vh>@clean simplest5.html</vh>
<v t="leo.20151115232449.2"><vh>檔案說明</vh></v>
<v t="leo.20151115232449.3" a="E"><vh>html 標註</vh>
<v t="leo.20151115232449.4" a="E"><vh>body 標註</vh>
<v t="leo.20151115232449.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151115232449.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151115232449.7"><vh>首頁</vh></v>
<v t="leo.20151115232449.8"><vh>自我介紹</vh></v>
<v t="leo.20151115232449.9"><vh>課程內容</vh></v>
<v t="leo.20151115232449.10"><vh>作業任務</vh></v>
<v t="leo.20151115232449.11"><vh>作業成果</vh></v>
<v t="leo.20151115232449.12"><vh>心得與自評</vh></v>
</v>
</v>
<v t="leo.20151115232449.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151115232457.1"><vh>@clean simplest6.html</vh>
<v t="leo.20151115232457.2"><vh>檔案說明</vh></v>
<v t="leo.20151115232457.3" a="E"><vh>html 標註</vh>
<v t="leo.20151115232457.4" a="E"><vh>body 標註</vh>
<v t="leo.20151115232457.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151115232457.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151115232457.7"><vh>首頁</vh></v>
<v t="leo.20151115232457.8"><vh>自我介紹</vh></v>
<v t="leo.20151115232457.9"><vh>課程內容</vh></v>
<v t="leo.20151115232457.10"><vh>作業任務</vh></v>
<v t="leo.20151115232457.11"><vh>作業成果</vh></v>
<v t="leo.20151115232457.12"><vh>心得與自評</vh></v>
</v>
</v>
<v t="leo.20151115232457.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151115232505.1"><vh>@clean simplest7.html</vh>
<v t="leo.20151115232505.2"><vh>檔案說明</vh></v>
<v t="leo.20151115232505.3" a="E"><vh>html 標註</vh>
<v t="leo.20151115232505.4" a="E"><vh>body 標註</vh>
<v t="leo.20151115232505.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151115232505.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151115232505.7"><vh>首頁</vh></v>
<v t="leo.20151115232505.8"><vh>自我介紹</vh></v>
<v t="leo.20151115232505.9"><vh>課程內容</vh></v>
<v t="leo.20151115232505.10"><vh>作業任務</vh></v>
<v t="leo.20151115232505.11"><vh>作業成果</vh></v>
<v t="leo.20151115232505.12"><vh>心得與自評</vh></v>
</v>
</v>
<v t="leo.20151115232505.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151115232511.1"><vh>@clean simplest8.html</vh>
<v t="leo.20151115232511.2"><vh>檔案說明</vh></v>
<v t="leo.20151115232511.3" a="E"><vh>html 標註</vh>
<v t="leo.20151115232511.4" a="E"><vh>body 標註</vh>
<v t="leo.20151115232511.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151115232511.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151115232511.7"><vh>首頁</vh></v>
<v t="leo.20151115232511.8"><vh>自我介紹</vh></v>
<v t="leo.20151115232511.9"><vh>課程內容</vh></v>
<v t="leo.20151115232511.10"><vh>作業任務</vh></v>
<v t="leo.20151115232511.11"><vh>作業成果</vh></v>
<v t="leo.20151115232511.12"><vh>心得與自評</vh></v>
</v>
</v>
<v t="leo.20151115232511.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151115232520.1"><vh>@clean simplest9.html</vh>
<v t="leo.20151115232520.2"><vh>檔案說明</vh></v>
<v t="leo.20151115232520.3" a="E"><vh>html 標註</vh>
<v t="leo.20151115232520.4" a="E"><vh>body 標註</vh>
<v t="leo.20151115232520.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151115232520.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151115232520.7"><vh>首頁</vh></v>
<v t="leo.20151115232520.8"><vh>自我介紹</vh></v>
<v t="leo.20151115232520.9"><vh>課程內容</vh></v>
<v t="leo.20151115232520.10"><vh>作業任務</vh></v>
<v t="leo.20151115232520.11"><vh>作業成果</vh></v>
<v t="leo.20151115232520.12"><vh>心得與自評</vh></v>
</v>
</v>
<v t="leo.20151115232520.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151119132034.1"><vh>@clean simplest10.html</vh>
<v t="leo.20151119132034.2"><vh>檔案說明</vh></v>
<v t="leo.20151119132034.3" a="E"><vh>html 標註</vh>
<v t="leo.20151119132034.4" a="E"><vh>body 標註</vh>
<v t="leo.20151119132034.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151119132034.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151119132034.7"><vh>首頁</vh></v>
<v t="leo.20151119132034.8"><vh>自我介紹</vh></v>
<v t="leo.20151119132034.9"><vh>課程內容</vh></v>
<v t="leo.20151119132034.10"><vh>作業任務</vh></v>
<v t="leo.20151119132034.11"><vh>作業成果</vh></v>
<v t="leo.20151119132034.12"><vh>心得與自評</vh></v>
</v>
</v>
<v t="leo.20151119132034.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151201235152.1"><vh>@clean simplest11.html</vh>
<v t="leo.20151201235152.2"><vh>檔案說明</vh></v>
<v t="leo.20151201235152.3" a="E"><vh>html 標註</vh>
<v t="leo.20151201235152.4" a="E"><vh>body 標註</vh>
<v t="leo.20151201235152.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151201235152.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151201235152.7"><vh>首頁</vh></v>
<v t="leo.20151201235152.8"><vh>自我介紹</vh></v>
<v t="leo.20151201235152.9"><vh>課程內容</vh></v>
<v t="leo.20151201235152.10"><vh>作業任務</vh></v>
<v t="leo.20151201235152.11"><vh>作業成果</vh></v>
<v t="leo.20151201235152.12"><vh>心得與自評</vh></v>
</v>
</v>
<v t="leo.20151201235152.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151201235202.1"><vh>@clean simplest12.html</vh>
<v t="leo.20151201235202.2"><vh>檔案說明</vh></v>
<v t="leo.20151201235202.3" a="E"><vh>html 標註</vh>
<v t="leo.20151201235202.4" a="E"><vh>body 標註</vh>
<v t="leo.20151201235202.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151201235202.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151201235202.7"><vh>首頁</vh></v>
<v t="leo.20151201235202.8"><vh>自我介紹</vh></v>
<v t="leo.20151201235202.9"><vh>課程內容</vh></v>
<v t="leo.20151201235202.10"><vh>作業任務</vh></v>
<v t="leo.20151201235202.11"><vh>作業成果</vh></v>
<v t="leo.20151201235202.12"><vh>心得與自評</vh></v>
</v>
</v>
<v t="leo.20151201235202.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151201235211.1"><vh>@clean simplest13.html</vh>
<v t="leo.20151201235211.2"><vh>檔案說明</vh></v>
<v t="leo.20151201235211.3" a="E"><vh>html 標註</vh>
<v t="leo.20151201235211.4" a="E"><vh>body 標註</vh>
<v t="leo.20151201235211.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151201235211.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151201235211.7"><vh>首頁</vh></v>
<v t="leo.20151201235211.8"><vh>自我介紹</vh></v>
<v t="leo.20151201235211.9"><vh>課程內容</vh></v>
<v t="leo.20151201235211.10"><vh>作業任務</vh></v>
<v t="leo.20151201235211.11"><vh>作業成果</vh></v>
<v t="leo.20151201235211.12"><vh>心得與自評</vh></v>
</v>
</v>
<v t="leo.20151201235211.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151201235217.1"><vh>@clean simplest14.html</vh>
<v t="leo.20151201235217.2"><vh>檔案說明</vh></v>
<v t="leo.20151201235217.3" a="E"><vh>html 標註</vh>
<v t="leo.20151201235217.4" a="E"><vh>body 標註</vh>
<v t="leo.20151201235217.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151201235217.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151201235217.7"><vh>首頁</vh></v>
<v t="leo.20151201235217.8"><vh>自我介紹</vh></v>
<v t="leo.20151201235217.9"><vh>課程內容</vh></v>
<v t="leo.20151201235217.10"><vh>作業任務</vh></v>
<v t="leo.20151201235217.11"><vh>作業成果</vh></v>
<v t="leo.20151201235217.12"><vh>心得與自評</vh></v>
</v>
</v>
<v t="leo.20151201235217.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151201235224.1"><vh>@clean simplest15.html</vh>
<v t="leo.20151201235224.2"><vh>檔案說明</vh></v>
<v t="leo.20151201235224.3" a="E"><vh>html 標註</vh>
<v t="leo.20151201235224.4" a="E"><vh>body 標註</vh>
<v t="leo.20151201235224.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151201235224.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151201235224.7"><vh>首頁</vh></v>
<v t="leo.20151201235224.8"><vh>自我介紹</vh></v>
<v t="leo.20151201235224.9"><vh>課程內容</vh></v>
<v t="leo.20151201235224.10"><vh>作業任務</vh></v>
<v t="leo.20151201235224.11"><vh>作業成果</vh></v>
<v t="leo.20151201235224.12"><vh>心得與自評</vh></v>
</v>
</v>
<v t="leo.20151201235224.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151201235230.1"><vh>@clean simplest16.html</vh>
<v t="leo.20151201235230.2"><vh>檔案說明</vh></v>
<v t="leo.20151201235230.3" a="E"><vh>html 標註</vh>
<v t="leo.20151201235230.4" a="E"><vh>body 標註</vh>
<v t="leo.20151201235230.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151201235230.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151201235230.7"><vh>首頁</vh></v>
<v t="leo.20151201235230.8"><vh>自我介紹</vh></v>
<v t="leo.20151201235230.9"><vh>課程內容</vh></v>
<v t="leo.20151201235230.10"><vh>作業任務</vh></v>
<v t="leo.20160121164943.1"><vh>作業成果</vh></v>
<v t="leo.20151201235230.12"><vh>心得與自評</vh></v>
</v>
</v>
<v t="leo.20151201235230.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151201235237.1" a="E"><vh>@clean simplest17.html</vh>
<v t="leo.20151201235237.2"><vh>檔案說明</vh></v>
<v t="leo.20151201235237.3" a="E"><vh>html 標註</vh>
<v t="leo.20151201235237.4" a="E"><vh>body 標註</vh>
<v t="leo.20151201235237.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151201235237.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151201235237.7"><vh>首頁</vh></v>
<v t="leo.20151201235237.8"><vh>自我介紹</vh></v>
<v t="leo.20151201235237.9"><vh>課程內容</vh></v>
<v t="leo.20151201235237.10"><vh>作業任務</vh></v>
<v t="leo.20151201235237.11"><vh>作業成果</vh></v>
<v t="leo.20151201235237.12"><vh>心得與自評</vh></v>
</v>
</v>
<v t="leo.20151201235237.13"><vh>script</vh></v>
</v>
</v>
</v>
<v t="leo.20151115135951.1"><vh>@clean simplest.html</vh>
<v t="leo.20151115135951.2"><vh>檔案說明</vh></v>
<v t="leo.20151115135951.3" a="E"><vh>html 標註</vh>
<v t="leo.20151115135951.4" a="E"><vh>body 標註</vh>
<v t="leo.20151115135951.5" a="E"><vh>div class="reveal"</vh>
<v t="leo.20151115135951.6" a="E"><vh>div class="slides"</vh>
<v t="leo.20151115135951.7"><vh>首頁</vh></v>
<v t="leo.20151115135951.8"><vh>資料彙整</vh></v>
<v t="leo.20151115135951.9"><vh>作業任務</vh></v>
<v t="leo.20151115135951.10"><vh>投影片</vh></v>
</v>
</v>
<v t="leo.20151115135951.11"><vh>script</vh></v>
</v>
</v>
</v>
<v t="amd.20150915170743.1"><vh>@clean v31ref.html</vh>
<v t="amd.20150915170743.2" a="E"><vh>html 標註</vh>
<v t="amd.20150915170743.3"><vh>head</vh></v>
<v t="amd.20150915170743.7" a="E"><vh>body</vh>
<v t="amd.20150915170743.9" a="E"><vh>div - reveal and slides</vh>
<v t="amd.20150915170743.10"><vh>一般單頁加上 anchor</vh></v>
<v t="amd.20150915170743.11"><vh>一般單頁</vh></v>
<v t="amd.20150915170743.12" a="E"><vh>垂直有下屬頁</vh>
<v t="amd.20150915170743.13"><vh>下屬頁之一</vh></v>
<v t="amd.20150915170743.14"><vh>下屬頁之二</vh></v>
<v t="amd.20150915170743.15"><vh>下屬頁之三</vh></v>
</v>
<v t="amd.20150915170743.16"><vh>一般頁面加上跳頁 anchor</vh></v>
<v t="amd.20150915170743.19"><vh>markdown 頁面</vh></v>
<v t="amd.20150915170743.20" a="E"><vh>逐一出現項目頁面</vh>
<v t="amd.20150915170743.21"><vh>Fragement 主頁面</vh></v>
<v t="amd.20150915170743.22" a="E"><vh>垂直之下屬頁面</vh>
<v t="amd.20150915170743.23"><vh>標題</vh></v>
<v t="amd.20150915170743.24"><vh>一般項目</vh></v>
<v t="amd.20150915170743.25"><vh>逐一跳出項目 grow</vh></v>
<v t="amd.20150915170743.26"><vh>逐一跳出項目 shrink</vh></v>
<v t="amd.20150915170743.27"><vh>逐一跳出項目 fade-out</vh></v>
<v t="amd.20150915170743.28"><vh>逐一跳出項目 cruuent-visible</vh></v>
<v t="amd.20150915170743.29"><vh>逐一跳出項目 highlight-red</vh></v>
<v t="amd.20150915170743.30"><vh>逐一跳出項目 highlight-blue</vh></v>
</v>
</v>
<v t="amd.20150915170743.59"><vh>背景填圖頁面</vh></v>
<v t="amd.20150915170743.75" a="E"><vh>內含程式碼頁面</vh>
<v t="amd.20150915170743.76" a="E"><vh>pre</vh>
<v t="amd.20150915170743.77"><vh>code</vh></v>
</v>
<v t="amd.20150915170743.78"><vh>p</vh></v>
</v>
<v t="amd.20150915170743.80" a="E"><vh>ul 資料表列</vh>
<v t="amd.20150915170743.81"><vh>li</vh></v>
<v t="amd.20150915170743.82"><vh>li</vh></v>
<v t="amd.20150915170743.83"><vh>li</vh></v>
<v t="amd.20150915170743.84"><vh>li</vh></v>
</v>
<v t="amd.20150915170743.86" a="E"><vh>ol 資料表列</vh>
<v t="amd.20150915170743.87"><vh>li</vh></v>
<v t="amd.20150915170743.88"><vh>li</vh></v>
<v t="amd.20150915170743.89"><vh>li</vh></v>
</v>
<v t="amd.20150915170743.91" a="E"><vh>表格頁面</vh>
<v t="amd.20150915170743.92" a="E"><vh>thead</vh>
<v t="amd.20150915170743.93" a="E"><vh>tr</vh>
<v t="amd.20150915170743.94"><vh>th</vh></v>
<v t="amd.20150915170743.95"><vh>th</vh></v>
<v t="amd.20150915170743.96"><vh>th</vh></v>
</v>
</v>
<v t="amd.20150915170743.97" a="E"><vh>tbody</vh>
<v t="amd.20150915170743.98"><vh>tr</vh>
<v t="amd.20150915170743.99"><vh>td</vh></v>
<v t="amd.20150915170743.100"><vh>td</vh></v>
<v t="amd.20150915170743.101"><vh>td</vh></v>
</v>
<v t="amd.20150915170743.102"><vh>tr</vh>
<v t="amd.20150915170743.103"><vh>td</vh></v>
<v t="amd.20150915170743.104"><vh>td</vh></v>
<v t="amd.20150915170743.105"><vh>td</vh></v>
</v>
<v t="amd.20150915170743.106"><vh>tr</vh>
<v t="amd.20150915170743.107"><vh>td</vh></v>
<v t="amd.20150915170743.108"><vh>td</vh></v>
<v t="amd.20150915170743.109"><vh>td</vh></v>
</v>
</v>
</v>
<v t="amd.20150915170743.111" a="E"><vh>Clever Quotes</vh>
<v t="amd.20150915170743.112"><vh>q</vh></v>
<v t="amd.20150915170743.113"><vh>blockquote</vh></v>
</v>
<v t="amd.20150915170743.135"><vh>h2 按下 b 或 . 可以 black 畫面</vh></v>
<v t="amd.20150915170743.137" a="E"><vh>h2 unordered list 頁面</vh>
<v t="amd.20150915170743.138"><vh>li</vh>
<v t="amd.20150915170743.139"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.140"><vh>li</vh>
<v t="amd.20150915170743.141"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.142"><vh>li</vh>
<v t="amd.20150915170743.143"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.144"><vh>li</vh>
<v t="amd.20150915170743.145"><vh>a</vh></v>
</v>
<v t="amd.20150915170743.146"><vh>li</vh></v>
</v>
<v t="amd.20150915170743.147"><vh>結束單頁</vh></v>
</v>
<v t="amd.20150915170743.148"><vh>script</vh></v>
</v>
</v>
</v>
</v>
<v t="amd.20151021113722.1"><vh>@path plugin</vh>
<v t="amd.20151021113731.1" a="E"><vh>@path liquid_tags</vh>
<v t="amd.20151021113745.1"><vh>@edit notebook.py</vh></v>
</v>
</v>
<v t="amd.20151021114454.1"><vh>@path user</vh>
<v t="amd.20151021114529.1"><vh>各組員必須自行建立 以下節點</vh></v>
<v t="amd.20151021114504.1" a="E"><vh>@path 40323107</vh>
<v t="amd.20151021114639.1"><vh>@edit 40323107_cp_w1_p.html</vh></v>
<v t="amd.20151021114516.1" a="E"><vh>@path pelican</vh>
<v t="amd.20151021114727.1"><vh>@edit publishconf.py</vh></v>
<v t="amd.20151021114712.1" a="E"><vh>@path content</vh>
<v t="amd.20151021114905.1"><vh>@edit 40323107_cp_w1.md</vh></v>
</v>
</v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="amd.20150913232631.1"></t>
<t tx="amd.20150913232631.2">QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    background-color: #ffffec; /* Leo's traditional tree color */
    selection-color: black; /* was white */
    selection-background-color: lightgrey;
    /* font-family: SansSerif; */
    /*font-family: DejaVu Sans Mono;*/
    font-family:YaHei Mono;
    /* 標題字型大小設定 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    background-color: cornsilk;
    selection-color: white;
    selection-background-color: blue;
    /*font-family: DejaVu Sans Mono;*/    
    font-family:YaHei Mono;
    /* 沒有特別對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The log panes */
QTextEdit {
    background-color: #f2fdff;
    selection-color: red;
    selection-background-color: blue;
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* log font 大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The body pane */
QTextEdit#richTextEdit {
    background-color: #fdf5f5; /* A kind of pink. */
    selection-color: white;
    selection-background-color: red;
    /*font-family: DejaVu Sans Mono;*/
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* 內文字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLabel {
    font-family:YaHei Mono;'CherryPy', 'pytz', 'mako', 'beautifulsoup4', 'pymysql', 'peewee'
    /* 下方的 Minibuffer 標題字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/* Editor labels */
QLineEdit#editorLabel {
    background-color: #ffffec;
    font-family:YaHei Mono;
    /* 沒有直接對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
    border: 2px;
    margin: 2px;
}</t>
<t tx="amd.20150913232631.3">horizontal: body pane to the left
vertical: body pane on the botton</t>
<t tx="amd.20150913233943.1">@language xml
@tabwidth -4
@others
</t>
<t tx="amd.20150913233943.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="amd.20150913233943.3">
&lt;head&gt;
@others
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;    
    &lt;!--Add support for earlier versions of Internet Explorer --&gt;
    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
&lt;/head&gt;
 
</t>
<t tx="amd.20150913233943.4">
&lt;meta charset="utf-8"&gt;
&lt;title&gt;2015 Fall CADP B Week1&lt;/title&gt;
</t>
<t tx="amd.20150913233943.5">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150913233943.6">
&lt;!-- Wrap the entire slide show in a div using the "reveal" class. --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150913233943.7">
&lt;!-- Wrap all slides in a single "slides" class --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150913233943.81">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
    </t>
<t tx="amd.20150913233943.82">&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
 
    </t>
<t tx="amd.20150913233943.83">&lt;script&gt;
        // Required, even if empty.
        Reveal.initialize({
        });
    &lt;/script&gt;
</t>
<t tx="amd.20150913234947.1">&lt;section id="title page"&gt;
&lt;section&gt;
標題頁面
&lt;/section&gt;
@others
&lt;/section&gt;
</t>
<t tx="amd.20150913235034.1">&lt;section&gt;
本日要點
&lt;/section&gt;</t>
<t tx="amd.20150913235123.1">&lt;section&gt;
結論
&lt;/section&gt;</t>
<t tx="amd.20150913235225.1">&lt;section&gt;
標題頁下的子頁
&lt;/section&gt;</t>
<t tx="amd.20150914000138.1">&lt;section&gt;
&lt;a href="http://continuum.io/downloads"&gt;Anaconda Python 下載&lt;/a&gt;
&lt;/section&gt;</t>
<t tx="amd.20150914000332.1">&lt;section id="設計的表達方式"&gt;
&lt;section&gt;
設計的表達方式
&lt;/section&gt;
@others
&lt;/section&gt;
</t>
<t tx="amd.20150914000332.2">&lt;section&gt;
協同模式下的網際雲端內容呈現
&lt;/section&gt;</t>
<t tx="amd.20150915155634.1">@language xml
@tabwidth -4
@others

</t>
<t tx="amd.20150915155634.10">&lt;!-- Any section element inside of this container is displayed as a slide --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;

</t>
<t tx="amd.20150915155634.100">
&lt;th&gt;Item&lt;/th&gt;
</t>
<t tx="amd.20150915155634.101">&lt;th&gt;Value&lt;/th&gt;
								</t>
<t tx="amd.20150915155634.102">&lt;th&gt;Quantity&lt;/th&gt;
							</t>
<t tx="amd.20150915155634.103">&lt;tbody&gt;
@others
&lt;/tbody&gt;
					</t>
<t tx="amd.20150915155634.104">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915155634.105">
&lt;td&gt;Apples&lt;/td&gt;
</t>
<t tx="amd.20150915155634.106">&lt;td&gt;$1&lt;/td&gt;
								</t>
<t tx="amd.20150915155634.107">&lt;td&gt;7&lt;/td&gt;
							</t>
<t tx="amd.20150915155634.108">&lt;tr&gt;
@others
&lt;/tr&gt;
							</t>
<t tx="amd.20150915155634.109">
&lt;td&gt;Lemonade&lt;/td&gt;
</t>
<t tx="amd.20150915155634.11">&lt;section id="fragments"&gt;
        &lt;h1&gt;課程說明&lt;/h1&gt;
    &lt;h3 class="fragment"&gt;課程名稱: 電腦輔助設計實習&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;開放 主動 自學與自評&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;使用 Solvespace 與 Creo 2.0&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;每週都有作業, 由各學員自評分數&lt;/h3&gt;
&lt;/section&gt;
	</t>
<t tx="amd.20150915155634.110">&lt;td&gt;$2&lt;/td&gt;
								</t>
<t tx="amd.20150915155634.111">&lt;td&gt;18&lt;/td&gt;
							</t>
<t tx="amd.20150915155634.112">&lt;tr&gt;
@others
&lt;/tr&gt;
						</t>
<t tx="amd.20150915155634.113">
&lt;td&gt;Bread&lt;/td&gt;
</t>
<t tx="amd.20150915155634.114">&lt;td&gt;$3&lt;/td&gt;
								</t>
<t tx="amd.20150915155634.115">&lt;td&gt;2&lt;/td&gt;
							</t>
<t tx="amd.20150915155634.116">&lt;section&gt;
&lt;h2&gt;Clever Quotes&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.117">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.118">
These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
</t>
<t tx="amd.20150915155634.119">&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
&lt;/blockquote&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.12">&lt;section id="fragments"&gt;
    &lt;h2&gt;實體輔助工具&lt;/h2&gt;
    &lt;h3 class="fragment"&gt;電動折疊自行車&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;HP 伺服器&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;3D 印表機零件&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;其他需要採購工具?&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;先模擬分析, 再實際驗證?&lt;/h3&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.120">&lt;section&gt;
&lt;h2&gt;Intergalactic Interconnections&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.121">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="amd.20150915155634.122">
You can link between slides internally,
&lt;a href="#/2/3"&gt;like this&lt;/a&gt;.
</t>
<t tx="amd.20150915155634.123">&lt;section&gt;
&lt;h2&gt;Speaker View&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.124">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.125">There's a &lt;a href="https://github.com/hakimel/reveal.js#speaker-notes"&gt;speaker view&lt;/a&gt;. It includes a timer, preview of the upcoming slide as well as your speaker notes.</t>
<t tx="amd.20150915155634.126">&lt;p&gt;
@others
&lt;/p&gt;
    &lt;aside class="notes"&gt;
    Oh hey, these are some notes. They'll be hidden in your presentation, but you can see them if you open the speaker notes window (hit 's' on your keyboard).
    &lt;/aside&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.127">Press the &lt;em&gt;S&lt;/em&gt; key to try it out.</t>
<t tx="amd.20150915155634.128">&lt;section&gt;
&lt;h2&gt;Export to PDF&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.129">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.13">&lt;section&gt;
@others
&lt;/section&gt;

						</t>
<t tx="amd.20150915155634.130">Presentations can be &lt;a href="https://github.com/hakimel/reveal.js#pdf-export"&gt;exported to PDF&lt;/a&gt;, here's an example:</t>
<t tx="amd.20150915155634.131">&lt;iframe src="//www.slideshare.net/slideshow/embed_code/42840540" width="445" height="355" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:3px solid #666; margin-bottom:5px; max-width: 100%;" allowfullscreen&gt; &lt;/iframe&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.132">&lt;section&gt;
&lt;h2&gt;Global State&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.133">&lt;p&gt;
@others
&lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.134">Set &lt;code&gt;data-state="something"&lt;/code&gt; on a slide and </t>
<t tx="amd.20150915155634.135">&lt;code&gt;"something"&lt;/code&gt;
will be added as a class to the document element when the slide is open. This lets you
apply broader style changes, like switching the page background.
					</t>
<t tx="amd.20150915155634.136">&lt;section data-state="customevent"&gt;
&lt;h2&gt;State Events&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.137">&lt;p&gt;
@others
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.138">
Additionally custom events can be triggered on a per slide basis by binding to the &lt;code&gt;data-state&lt;/code&gt; name.
</t>
<t tx="amd.20150915155634.139">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.14">&lt;section&gt;
    &lt;h2&gt;Vertical Slides&lt;/h2&gt;
    &lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
    &lt;p&gt;
    Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.
    &lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#" class="navigate-down"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
    &lt;/a&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915155634.140">&lt;code class="javascript" data-trim contenteditable style="font-size: 18px;"&gt;
Reveal.addEventListener( 'customevent', function() {
	console.log( '"customevent" has fired' );
} );
					&lt;/code&gt;</t>
<t tx="amd.20150915155634.141">&lt;section&gt;
&lt;h2&gt;Take a Moment&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.142">&lt;p&gt;
Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
&lt;/p&gt;
&lt;/section&gt;

				
					</t>
<t tx="amd.20150915155634.143">&lt;section&gt;
&lt;h2&gt;Much more&lt;/h2&gt;
    &lt;ul&gt;
    @others
    &lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.145">&lt;li&gt;Right-to-left support&lt;/li&gt;
</t>
<t tx="amd.20150915155634.146">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.147">&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;</t>
<t tx="amd.20150915155634.148">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.149">&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;</t>
<t tx="amd.20150915155634.15">&lt;section&gt;
    &lt;h2&gt;Basement Level 1&lt;/h2&gt;
    &lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915155634.150">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.151">&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;</t>
<t tx="amd.20150915155634.152">&lt;li&gt;
@others
&lt;/li&gt;
					</t>
<t tx="amd.20150915155634.153">&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;</t>
<t tx="amd.20150915155634.154">&lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;section&gt;
					</t>
<t tx="amd.20150915155634.158">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
		</t>
<t tx="amd.20150915155634.159">&lt;script src="js/reveal.js"&gt;&lt;/script&gt;

		</t>
<t tx="amd.20150915155634.16">&lt;section&gt;
    &lt;h2&gt;Basement Level 2&lt;/h2&gt;
    &lt;p&gt;That's it, time to go back up.&lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#/2"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
    &lt;/a&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915155634.160">&lt;script&gt;

			// Full list of configuration options available at:
			// https://github.com/hakimel/reveal.js#configuration
			Reveal.initialize({
				controls: true,
				progress: true,
				history: true,
				center: true,

				transition: 'slide', // none/fade/slide/convex/concave/zoom

				// Optional reveal.js plugins
				dependencies: [
					{ src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
					{ src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
					{ src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
					{ src: 'plugin/zoom-js/zoom.js', async: true },
					{ src: 'plugin/notes/notes.js', async: true }
				]
			});

		&lt;/script&gt;

	</t>
<t tx="amd.20150915155634.17">&lt;section&gt;
    &lt;h2&gt;Slides&lt;/h2&gt;
    &lt;p&gt;
    Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.18">&lt;section&gt;
    &lt;h2&gt;Point of View&lt;/h2&gt;
    &lt;p&gt;
    Press &lt;strong&gt;ESC&lt;/strong&gt; to enter the slide overview.
    &lt;/p&gt;
    &lt;p&gt;
    Hold down alt and click on any element to zoom in on it using &lt;a href="http://lab.hakim.se/zoom-js"&gt;zoom.js&lt;/a&gt;. Alt + click anywhere to zoom back out.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.19">&lt;section&gt;
    &lt;h2&gt;Touch Optimized&lt;/h2&gt;
    &lt;p&gt;
    Presentations look great on touch devices, like mobile phones and tablets. Simply swipe through your slides.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="amd.20150915155634.20">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
        ## Markdown support
        
        Write content using inline or external Markdown.
        Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
        
            ```
            &lt;section data-markdown&gt;
              ## Markdown support
            
              Write content using inline or external Markdown.
              Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
            &lt;/section&gt;
            ```
    &lt;/script&gt;
&lt;/section&gt;


						</t>
<t tx="amd.20150915155634.21">&lt;section&gt;
    @others
&lt;/section&gt;

						</t>
<t tx="amd.20150915155634.28">&lt;section&gt;
@others
&lt;/section&gt;


						</t>
<t tx="amd.20150915155634.29">&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.3">&lt;head&gt;
@others
&lt;/head&gt;

</t>
<t tx="amd.20150915155634.30">&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.31">&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.32">&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.33">&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.34">&lt;p class="fragment highlight-red"&gt;highlight-red&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.35">&lt;p class="fragment highlight-blue"&gt;highlight-blue&lt;/p&gt;


				
					</t>
<t tx="amd.20150915155634.36">&lt;section id="transitions"&gt;
&lt;h2&gt;Transition Styles&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.37">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.38">
You can select from different transitions, like: &lt;br&gt;
&lt;a href="?transition=none#/transitions"&gt;None&lt;/a&gt; -
</t>
<t tx="amd.20150915155634.39">&lt;a href="?transition=fade#/transitions"&gt;Fade&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.4">&lt;meta charset="utf-8"&gt;

&lt;title&gt;2015 Fall 電腦輔助設計實習 甲班&lt;/title&gt;

</t>
<t tx="amd.20150915155634.40">&lt;a href="?transition=slide#/transitions"&gt;Slide&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.41">&lt;a href="?transition=convex#/transitions"&gt;Convex&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.42">&lt;a href="?transition=concave#/transitions"&gt;Concave&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.43">&lt;a href="?transition=zoom#/transitions"&gt;Zoom&lt;/a&gt;
					</t>
<t tx="amd.20150915155634.44">&lt;section id="themes"&gt;
&lt;h2&gt;Themes&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.45">&lt;p&gt;
@others
&lt;/p&gt;
				&lt;/section&gt;

				&lt;section&gt;
					&lt;section data-background="#dddddd"&gt;
						</t>
<t tx="amd.20150915155634.46">
reveal.js comes with a few themes built in: &lt;br&gt;
&lt;!-- Hacks to swap themes after the page has loaded. Not flexible and only intended for the reveal.js demo deck. --&gt;
&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/black.css'); return false;"&gt;Black (default)&lt;/a&gt; -
</t>
<t tx="amd.20150915155634.47">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/white.css'); return false;"&gt;White&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.48">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/league.css'); return false;"&gt;League&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.49">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/sky.css'); return false;"&gt;Sky&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.5">&lt;meta name="description" content="2015Fall CADP"&gt;
&lt;meta name="author" content="KMOL"&gt;
&lt;meta name="apple-mobile-web-app-capable" content="yes" /&gt;
&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" /&gt;
		</t>
<t tx="amd.20150915155634.50">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/beige.css'); return false;"&gt;Beige&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.51">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/simple.css'); return false;"&gt;Simple&lt;/a&gt; </t>
<t tx="amd.20150915155634.52">&lt;br&gt;
						&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/serif.css'); return false;"&gt;Serif&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.53">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/blood.css'); return false;"&gt;Blood&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.54">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/night.css'); return false;"&gt;Night&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.55">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/moon.css'); return false;"&gt;Moon&lt;/a&gt; -
						</t>
<t tx="amd.20150915155634.56">&lt;a href="#" onclick="document.getElementById('theme').setAttribute('href','css/theme/solarized.css'); return false;"&gt;Solarized&lt;/a&gt;
					</t>
<t tx="amd.20150915155634.57">&lt;h2&gt;Slide Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915155634.58">&lt;p&gt;
@others
&lt;/p&gt;
						</t>
<t tx="amd.20150915155634.59">
Set &lt;code&gt;data-background="#dddddd"&lt;/code&gt; on a slide to change the background color. All CSS color formats are supported.
</t>
<t tx="amd.20150915155634.60">&lt;a href="#" class="navigate-down"&gt;
							&lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
						&lt;/a&gt;
					&lt;/section&gt;
					&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png"&gt;
						</t>
<t tx="amd.20150915155634.61">&lt;h2&gt;Image Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915155634.62">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915155634.63">&lt;code&gt;&amp;lt;section data-background="image.png"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915155634.64">&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
						</t>
<t tx="amd.20150915155634.65">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;
&lt;section data-background-video="https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.mp4,https://s3.amazonaws.com/static.slid.es/site/homepage/v1/homepage-video-editor.webm" data-background-color="#000000"&gt;
						</t>
<t tx="amd.20150915155634.66">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;
&lt;/code&gt;</t>
<t tx="amd.20150915155634.67">&lt;div style="background-color: rgba(0, 0, 0, 0.9); color: #fff; padding: 20px;"&gt;
@others
&lt;/div&gt;
&lt;/section&gt;

						</t>
<t tx="amd.20150915155634.68">&lt;section data-background="http://i.giphy.com/90F8aUepslB84.gif"&gt;
&lt;h2&gt;Video Backgrounds&lt;/h2&gt;
</t>
<t tx="amd.20150915155634.69">&lt;pre&gt;
@others
&lt;/pre&gt;
						</t>
<t tx="amd.20150915155634.7">&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui"&gt;

    &lt;link rel="stylesheet" href="css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/black.css" id="theme"&gt;

    &lt;!-- Code syntax highlighting --&gt;
    &lt;link rel="stylesheet" href="lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;
	</t>
<t tx="amd.20150915155634.70">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-video="video.mp4,video.webm"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915155634.71">&lt;h2&gt;... and GIFs!&lt;/h2&gt;
&lt;/section&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.72">&lt;section data-transition="slide" data-background="#4d7e65" data-background-transition="zoom"&gt;
&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.73">&lt;p&gt;
						Different background transitions are available via the backgroundTransition option. This one's called "zoom".
					&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.74">&lt;pre&gt;
@others
&lt;/pre&gt;
				&lt;/section&gt;

				&lt;section data-transition="slide" data-background="#b5533c" data-background-transition="zoom"&gt;
					</t>
<t tx="amd.20150915155634.75">&lt;code&gt;Reveal.configure({ backgroundTransition: 'zoom' })&lt;/code&gt;</t>
<t tx="amd.20150915155634.76">&lt;h2&gt;Background Transitions&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.77">&lt;p&gt;
You can override background transitions per-slide.
&lt;/p&gt;
					</t>
<t tx="amd.20150915155634.78">&lt;pre&gt;
@others
&lt;/pre&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.79">&lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background-transition="zoom"&amp;gt;&lt;/code&gt;</t>
<t tx="amd.20150915155634.8">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150915155634.80">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.81">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="amd.20150915155634.82">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="amd.20150915155634.83">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="amd.20150915155634.85">&lt;section&gt;
&lt;h2&gt;Marvelous List&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.86">&lt;ul&gt;
@others
&lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915155634.87">
&lt;li&gt;No order here&lt;/li&gt;
</t>
<t tx="amd.20150915155634.88">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.89">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.9">&lt;div class="reveal"&gt;
@others
&lt;/div&gt;

</t>
<t tx="amd.20150915155634.90">&lt;li&gt;Or here&lt;/li&gt;
					</t>
<t tx="amd.20150915155634.91">&lt;section&gt;
&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.92">&lt;ol&gt;
@others
&lt;/ol&gt;
&lt;/section&gt;

					</t>
<t tx="amd.20150915155634.93">
&lt;li&gt;One is smaller than...&lt;/li&gt;
</t>
<t tx="amd.20150915155634.94">&lt;li&gt;Two is smaller than...&lt;/li&gt;
						</t>
<t tx="amd.20150915155634.95">&lt;li&gt;Three!&lt;/li&gt;
					</t>
<t tx="amd.20150915155634.96">&lt;section&gt;
&lt;h2&gt;Tabular Tables&lt;/h2&gt;
					</t>
<t tx="amd.20150915155634.97">&lt;table&gt;
@others
&lt;/table&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915155634.98">&lt;thead&gt;
@others
&lt;/thead&gt;
</t>
<t tx="amd.20150915155634.99">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915160450.1">&lt;section id="fragments"&gt;
&lt;h2&gt;Fragments&lt;/h2&gt;
&lt;p&gt;Hit the next arrow...&lt;/p&gt;
&lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
&lt;p&gt;
    &lt;span class="fragment"&gt;... a&lt;/span&gt; 
    &lt;span class="fragment"&gt;fragmented&lt;/span&gt;
    &lt;span class="fragment"&gt;slide.&lt;/span&gt;
&lt;/p&gt;

&lt;aside class="notes"&gt;
This slide has fragments which are also stepped through in the notes window.
&lt;/aside&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915161424.1">&lt;h2&gt;Fragment Styles&lt;/h2&gt;</t>
<t tx="amd.20150915170743.1">@language xml
@tabwidth -4
@others

</t>
<t tx="amd.20150915170743.10">&lt;section&gt;
    &lt;h1&gt;Reveal.js 使用說明&lt;/h1&gt;
    &lt;h3&gt;The HTML Presentation Framework 框架&lt;/h3&gt;
    &lt;p&gt;
    &lt;small&gt;
    Created by &lt;a href="http://hakim.se"&gt;Hakim El Hattab&lt;/a&gt; / 
    &lt;a href="http://twitter.com/hakimel"&gt;@hakimel&lt;/a&gt;
    &lt;/small&gt;
    &lt;/p&gt;
&lt;/section&gt;
	</t>
<t tx="amd.20150915170743.100">&lt;td&gt;$1&lt;/td&gt;
								</t>
<t tx="amd.20150915170743.101">&lt;td&gt;7&lt;/td&gt;
							</t>
<t tx="amd.20150915170743.102">&lt;tr&gt;
@others
&lt;/tr&gt;
							</t>
<t tx="amd.20150915170743.103">
&lt;td&gt;Lemonade&lt;/td&gt;
</t>
<t tx="amd.20150915170743.104">&lt;td&gt;$2&lt;/td&gt;
								</t>
<t tx="amd.20150915170743.105">&lt;td&gt;18&lt;/td&gt;
							</t>
<t tx="amd.20150915170743.106">&lt;tr&gt;
@others
&lt;/tr&gt;
						</t>
<t tx="amd.20150915170743.107">
&lt;td&gt;Bread&lt;/td&gt;
</t>
<t tx="amd.20150915170743.108">&lt;td&gt;$3&lt;/td&gt;
								</t>
<t tx="amd.20150915170743.109">&lt;td&gt;2&lt;/td&gt;
							</t>
<t tx="amd.20150915170743.11">&lt;section&gt;
    &lt;h2&gt;Hello There&lt;/h2&gt;
    &lt;p&gt;
reveal.js enables you to create beautiful interactive slide decks using HTML. This presentation will show you examples of what it can do.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.111">&lt;section&gt;
&lt;h2&gt;Clever Quotes&lt;/h2&gt;
    &lt;p&gt;
    @others
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.112">These guys come in two forms, inline: &lt;q cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
&amp;ldquo;The nice thing about standards is that there are so many to choose from&amp;rdquo;&lt;/q&gt; and block:
</t>
<t tx="amd.20150915170743.113">&lt;blockquote cite="http://searchservervirtualization.techtarget.com/definition/Our-Favorite-Technology-Quotations"&gt;
						&amp;ldquo;For years there has been a theory that millions of monkeys typing at random on millions of typewriters would
						reproduce the entire works of Shakespeare. The Internet has proven this theory to be untrue.&amp;rdquo;
&lt;/blockquote&gt;
					</t>
<t tx="amd.20150915170743.12">&lt;section&gt;
&lt;h1&gt;以下為垂直頁面&lt;/h1&gt;
以下為垂直頁
@others
&lt;/section&gt;

						</t>
<t tx="amd.20150915170743.13">&lt;section&gt;
    &lt;h2&gt;Vertical Slides&lt;/h2&gt;
    &lt;p&gt;Slides can be nested inside of each other.&lt;/p&gt;
    &lt;p&gt;
    Use the &lt;em&gt;Space&lt;/em&gt; key to navigate through all slides.
    &lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#" class="navigate-down"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Down arrow"&gt;
    &lt;/a&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915170743.135">&lt;section&gt;
    &lt;h2&gt;Take a Moment&lt;/h2&gt;
    &lt;p&gt;
    Press B or . on your keyboard to pause the presentation. This is helpful when you're on stage and want to take distracting slides off the screen.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.137">&lt;section&gt;
&lt;h2&gt;Much more&lt;/h2&gt;
    &lt;ul&gt;
    @others
    &lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.138">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.139">&lt;a href="https://github.com/hakimel/reveal.js#auto-sliding"&gt;Auto-progression&lt;/a&gt;</t>
<t tx="amd.20150915170743.14">&lt;section&gt;
    &lt;h2&gt;Basement Level 1&lt;/h2&gt;
    &lt;p&gt;Nested slides are useful for adding additional detail underneath a high level horizontal slide.&lt;/p&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915170743.140">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.141">&lt;a href="https://github.com/hakimel/reveal.js#parallax-background"&gt;Parallax backgrounds&lt;/a&gt;</t>
<t tx="amd.20150915170743.142">&lt;li&gt;
@others
&lt;/li&gt;
					</t>
<t tx="amd.20150915170743.143">&lt;a href="https://github.com/hakimel/reveal.js#keyboard-bindings"&gt;Custom keyboard bindings&lt;/a&gt;</t>
<t tx="amd.20150915170743.144">&lt;li&gt;
@others
&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.145">&lt;a href="https://github.com/hakimel/reveal.js#api"&gt;Extensive JavaScript API&lt;/a&gt;</t>
<t tx="amd.20150915170743.146">&lt;li&gt;Right-to-left support&lt;/li&gt;
</t>
<t tx="amd.20150915170743.147">&lt;section style="text-align: left;"&gt;
&lt;h1&gt;THE END&lt;/h1&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.148">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // Full list of configuration options available at:
    // https://github.com/hakimel/reveal.js#configuration
    Reveal.initialize({
        controls: true,
        progress: true,
        history: true,
        center: true,

        transition: 'slide', // none/fade/slide/convex/concave/zoom

        // Optional reveal.js plugins
        dependencies: [
            { src: 'lib/js/classList.js', condition: function() { return !document.body.classList; } },
            { src: 'plugin/markdown/marked.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
            { src: 'plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
            { src: 'plugin/highlight/highlight.js', async: true, condition: function() { return !!document.querySelector( 'pre code' ); }, callback: function() { hljs.initHighlightingOnLoad(); } },
            { src: 'plugin/zoom-js/zoom.js', async: true },
            { src: 'plugin/notes/notes.js', async: true }
        ]
    });
&lt;/script&gt;

	

		
		</t>
<t tx="amd.20150915170743.15">&lt;section&gt;
    &lt;h2&gt;Basement Level 2&lt;/h2&gt;
    &lt;p&gt;That's it, time to go back up.&lt;/p&gt;
    &lt;br&gt;
    &lt;a href="#/2"&gt;
    &lt;img width="178" height="238" data-src="https://s3.amazonaws.com/hakim-static/reveal-js/arrow.png" alt="Up arrow" style="transform: rotate(180deg); -webkit-transform: rotate(180deg);"&gt;
    &lt;/a&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915170743.16">&lt;section&gt;
    &lt;h2&gt;Slides&lt;/h2&gt;
    &lt;p&gt;
    Not a coder? Not a problem. There's a fully-featured visual editor for authoring these, try it out at &lt;a href="http://slides.com" target="_blank"&gt;http://slides.com&lt;/a&gt;.
    &lt;/p&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.19">&lt;section data-markdown&gt;
    &lt;script type="text/template"&gt;
        ## Markdown support
        
        Write content using inline or external Markdown.
        Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
        
            ```
            &lt;section data-markdown&gt;
              ## Markdown support
            
              Write content using inline or external Markdown.
              Instructions and more info available in the [readme](https://github.com/hakimel/reveal.js#markdown).
            &lt;/section&gt;
            ```
    &lt;/script&gt;
&lt;/section&gt;


						</t>
<t tx="amd.20150915170743.2">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
@others
&lt;/html&gt;</t>
<t tx="amd.20150915170743.20">&lt;section&gt;
逐一出現
    @others
&lt;/section&gt;

						</t>
<t tx="amd.20150915170743.21">&lt;section id="fragments"&gt;
    &lt;h2&gt;Fragments&lt;/h2&gt;
    &lt;p&gt;Hit the next arrow...&lt;/p&gt;
    &lt;p class="fragment"&gt;... to step through ...&lt;/p&gt;
    &lt;p&gt;
        &lt;span class="fragment"&gt;... a&lt;/span&gt; 
        &lt;span class="fragment"&gt;fragmented&lt;/span&gt;
        &lt;span class="fragment"&gt;slide.&lt;/span&gt;
    &lt;/p&gt;
    
    &lt;aside class="notes"&gt;
    This slide has fragments which are also stepped through in the notes window.
    &lt;/aside&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915170743.22">&lt;section&gt;
@others
&lt;/section&gt;


						</t>
<t tx="amd.20150915170743.23">&lt;h2&gt;Fragment Styles&lt;/h2&gt;</t>
<t tx="amd.20150915170743.24">&lt;p&gt;There's different types of fragments, like:&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.25">&lt;p class="fragment grow"&gt;grow&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.26">&lt;p class="fragment shrink"&gt;shrink&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.27">&lt;p class="fragment fade-out"&gt;fade-out&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.28">&lt;p class="fragment current-visible"&gt;current-visible&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.29">&lt;p class="fragment highlight-red"&gt;highlight-red&lt;/p&gt;
						</t>
<t tx="amd.20150915170743.3">&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;檔案標題&lt;/title&gt;
&lt;meta name="description" content="A framework for easily creating beautiful presentations using HTML"&gt;
&lt;meta name="author" content="作者"&gt;
&lt;meta name="apple-mobile-web-app-capable" content="yes" /&gt;
&lt;meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" /&gt;
&lt;meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui"&gt;

    &lt;link rel="stylesheet" href="css/reveal.css"&gt;
    &lt;link rel="stylesheet" href="css/theme/black.css" id="theme"&gt;

    &lt;!-- Code syntax highlighting --&gt;
    &lt;link rel="stylesheet" href="lib/css/zenburn.css"&gt;

    &lt;!-- Printing and PDF exports --&gt;
    &lt;script&gt;
        var link = document.createElement( 'link' );
        link.rel = 'stylesheet';
        link.type = 'text/css';
        link.href = window.location.search.match( /print-pdf/gi ) ? 'css/print/pdf.css' : 'css/print/paper.css';
        document.getElementsByTagName( 'head' )[0].appendChild( link );
    &lt;/script&gt;

    &lt;!--[if lt IE 9]&gt;
    &lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
    &lt;![endif]--&gt;	
&lt;/head&gt;

</t>
<t tx="amd.20150915170743.30">&lt;p class="fragment highlight-blue"&gt;highlight-blue&lt;/p&gt;


				
					</t>
<t tx="amd.20150915170743.59">&lt;section data-background="https://s3.amazonaws.com/hakim-static/reveal-js/image-placeholder.png" data-background-repeat="repeat" data-background-size="100px"&gt;
&lt;h2&gt;Tiled Backgrounds&lt;/h2&gt;
    &lt;pre&gt;
    &lt;code style="word-wrap: break-word;"&gt;&amp;lt;section data-background="image.png" data-background-repeat="repeat" data-background-size="100px"&amp;gt;
    &lt;/code&gt;
    &lt;/pre&gt;
&lt;/section&gt;
						</t>
<t tx="amd.20150915170743.7">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150915170743.75">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.76">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="amd.20150915170743.77">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="amd.20150915170743.78">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="amd.20150915170743.80">&lt;section&gt;
&lt;h2&gt;Marvelous List&lt;/h2&gt;
    &lt;ul&gt;
    @others
    &lt;/ul&gt;
&lt;/section&gt;
					</t>
<t tx="amd.20150915170743.81">&lt;li&gt;No order here&lt;/li&gt;
</t>
<t tx="amd.20150915170743.82">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.83">&lt;li&gt;Or here&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.84">&lt;li&gt;Or here&lt;/li&gt;
					</t>
<t tx="amd.20150915170743.86">&lt;section&gt;
&lt;h2&gt;Fantastic Ordered List&lt;/h2&gt;
    &lt;ol&gt;
    @others
    &lt;/ol&gt;
&lt;/section&gt;

					</t>
<t tx="amd.20150915170743.87">&lt;li&gt;One is smaller than...&lt;/li&gt;
</t>
<t tx="amd.20150915170743.88">&lt;li&gt;Two is smaller than...&lt;/li&gt;
						</t>
<t tx="amd.20150915170743.89">&lt;li&gt;Three!&lt;/li&gt;
					</t>
<t tx="amd.20150915170743.9">&lt;div class="reveal"&gt;
    &lt;!-- Any section element inside of this container is displayed as a slide --&gt;
    &lt;div class="slides"&gt;
    @others
    &lt;/div&gt;
&lt;/div&gt;



</t>
<t tx="amd.20150915170743.91">&lt;section&gt;
&lt;h2&gt;Tabular Tables&lt;/h2&gt;
    &lt;table&gt;
    @others
    &lt;/table&gt;
&lt;/section&gt;


					</t>
<t tx="amd.20150915170743.92">&lt;thead&gt;
@others
&lt;/thead&gt;
</t>
<t tx="amd.20150915170743.93">&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915170743.94">&lt;th&gt;Item&lt;/th&gt;
</t>
<t tx="amd.20150915170743.95">&lt;th&gt;Value&lt;/th&gt;
								</t>
<t tx="amd.20150915170743.96">&lt;th&gt;Quantity&lt;/th&gt;
							</t>
<t tx="amd.20150915170743.97">&lt;tbody&gt;
@others
&lt;/tbody&gt;
					</t>
<t tx="amd.20150915170743.98">
&lt;tr&gt;
@others
&lt;/tr&gt;
</t>
<t tx="amd.20150915170743.99">
&lt;td&gt;Apples&lt;/td&gt;
</t>
<t tx="amd.20150915172241.1">&lt;section id="fragments"&gt;
        &lt;h1&gt;自評說明&lt;/h1&gt;
    &lt;h3 class="fragment"&gt;時效內的 Github 倉儲內容&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;完全開放的學員作業內容&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;彼此間可以互相學習&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;存證內容: Github, copy.com, Vimeo 等&lt;/h3&gt;
    &lt;h3 class="fragment"&gt;要怎麼收穫, 先怎麼栽!&lt;/h3&gt;
&lt;/section&gt;
	</t>
<t tx="amd.20150915173703.1">&lt;section&gt;
    &lt;h2&gt;Pretty Code&lt;/h2&gt;
    @others
&lt;/section&gt;
					</t>
<t tx="amd.20150915173703.2">&lt;pre&gt;
    &lt;code data-trim contenteditable&gt;
    @others
    &lt;/code&gt;
&lt;/pre&gt;
					</t>
<t tx="amd.20150915173703.3">function linkify( selector ) {
  if( supports3DTransforms ) {

    var nodes = document.querySelectorAll( selector );

    for( var i = 0, len = nodes.length; i &amp;lt; len; i++ ) {
      var node = nodes[i];

      if( !node.className ) {
        node.className += ' roll';
      }
    }
  }
}
</t>
<t tx="amd.20150915173703.4">&lt;p&gt;
Code syntax highlighting courtesy of &lt;a href="http://softwaremaniacs.org/soft/highlight/en/description/"&gt;highlight.js&lt;/a&gt;.
&lt;/p&gt;



					</t>
<t tx="amd.20150915204710.1">&lt;section&gt;
&lt;h1&gt;嵌入 Vimeo 影片&lt;/h1&gt;
&lt;iframe src="https://player.vimeo.com/video/137724068" width="500" height="281" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen&gt;&lt;/iframe&gt; &lt;p&gt;&lt;a href="https://vimeo.com/137724068"&gt;Welcome Speech&lt;/a&gt; from &lt;a href="https://vimeo.com/user24079973"&gt;虎尾科大機械設計工程系 KMOL&lt;/a&gt; on &lt;a href="https://vimeo.com"&gt;Vimeo&lt;/a&gt;.&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="amd.20150915211341.1">@language xml
@tabwidth -4
@others

</t>
<t tx="amd.20150915211351.1">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="amd.20150915211351.12">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務成果&lt;/h2&gt;
        &lt;p&gt;1.倉儲網址&lt;/p&gt;
        &lt;p&gt;2.測試網頁&lt;/p&gt;
        &lt;p&gt;3.自製影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;倉儲網址&lt;/h2&gt;
        &lt;p&gt;&lt;a href="https://github.com/40323107/2015fallcadpa/tree/gh-pages"&gt;40323107 - Github&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;測試網頁&lt;/h2&gt;
        &lt;p&gt;&lt;a href="http://www.google.com"&gt;google&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自製影片&lt;/h2&gt;
        &lt;p&gt;1.如何輸出字串&lt;/p&gt;
        &lt;p&gt;2.如何創建倉儲&lt;/p&gt;
        &lt;p&gt;3.如何新建分支&lt;/p&gt;
        &lt;p&gt;4.如何新建網頁&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;		
</t>
<t tx="amd.20150915211351.15">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="amd.20150915211351.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="amd.20150915211351.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150915211351.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="amd.20150915211351.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;四設計二甲&lt;/h2&gt;
    &lt;p&gt;40323107&lt;/p&gt;
    &lt;p&gt;廖佑珊&lt;/p&gt;			
&lt;/section&gt;
	
</t>
<t tx="amd.20150915211351.9">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務一&lt;/h2&gt;
        &lt;p&gt;1.任務說明&lt;/p&gt;
        &lt;p&gt;2.參考網址&lt;/p&gt;
        &lt;p&gt;3.參考影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2 align="left"&gt;任務說明&lt;/h2&gt;
        &lt;p align="left"&gt;(1)建立個人 Github 課程倉儲 。(※名稱為 2015cadp)&lt;/p&gt;
        &lt;p align="left"&gt;(2)使用 Git 在 Github 建立分支。                                &lt;/p&gt;
        &lt;p align="left"&gt;(3)使用 SciTE 新增網頁，並利用 git 推送至 Github。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考網址&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt; &lt;a href="http://wordpress-2015course.rhcloud.com/?p=3637"&gt;w1&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考影片&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt; &lt;a href="https://player.vimeo.com/video/140277094"&gt;Vimeo - W1 - 1&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/140277188"&gt;Vimeo - W1 - 2&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/140281702"&gt;Vimeo - W1 - 3&lt;/a&gt;&lt;/p&gt;
        &lt;/section&gt;
&lt;/section&gt;


</t>
<t tx="amd.20150917085040.1">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="amd.20150919102739.1">主要為 reveal.js 的簡報目錄架構, 其他子目錄為

images - 存放簡報與 pelican 網誌所需要的影像檔案

pelican - 存放 pelican 專案資料檔, 並且設法讓 pelican 所產生的 output 檔案直接存放到上層 reveal.js 根目錄

content/notebook - 存放 Jupyter 的 IPython notebook 檔案, 然後再由 pelican 設定, 將內容放入 blog 文章中

</t>
<t tx="amd.20150919103357.1">打算利用

pelican pelican -o ./../ -s publishconf.py

-o 指定 ouput 所在目錄, 這裡使用上一層目錄, 

-s 則指定 setting, 這裡採用 publishconf.py 中的設定

將位於專案中 pelican 目錄內的 .md 檔案, 轉為 html 網誌格式, 然後存在 reveal.js 的架構目錄中

也就是 index.html 是由 pelican 控制</t>
<t tx="amd.20150919113957.1"></t>
<t tx="amd.20150919114010.1"></t>
<t tx="amd.20150919120205.1"></t>
<t tx="amd.20150919124128.1">@language python
import os
os.system("pelican pelican/content -o ./ -s pelican/publishconf.py -t ../../theme/pelican-octopress")
g.es("user pelican 執行完畢")</t>
<t tx="amd.20151006113136.1"></t>
<t tx="amd.20151007224830.1">安裝

sudo pip3 install jupyter

執行

jupyter notebook
</t>
<t tx="amd.20151021113722.1"></t>
<t tx="amd.20151021113731.1"></t>
<t tx="amd.20151021114454.1"></t>
<t tx="amd.20151021114504.1"></t>
<t tx="amd.20151021114516.1"></t>
<t tx="amd.20151021114529.1"></t>
<t tx="amd.20151021114712.1"></t>
<t tx="amd.20151021120245.1">@language python
import os
os.system("pelican pelican/content -o ./ -s pelican/publishconf.py -t theme/pelican-octopress")
g.es("admin pelican 執行完畢")</t>
<t tx="ibm.20150918175403.1">@language xml
@tabwidth -4
@others

</t>
<t tx="ibm.20150918175403.10">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	</t>
<t tx="ibm.20150918175403.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="ibm.20150918175403.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;2015CP W1&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
&lt;/html&gt;</t>
<t tx="ibm.20150918175403.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="ibm.20150918175403.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="ibm.20150918175403.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="ibm.20150918175403.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;電腦輔助設計與實習&lt;/h1&gt;
    &lt;p&gt;第1週教學內容&lt;/p&gt;		
&lt;/section&gt;
	</t>
<t tx="ibm.20150918175403.8">&lt;section id="hw-task-one"&gt;
    &lt;h1&gt;課程規劃&lt;/h1&gt;
    &lt;p&gt;教科書&lt;/p&gt;
    &lt;p&gt;請參考 &lt;a href="http://openbookproject.net/thinkcs/python/english3e/"&gt;http://openbookproject.net/thinkcs/python/english3e/&lt;/a&gt;
&lt;/section&gt;
				</t>
<t tx="ibm.20150918175403.9">&lt;section&gt;
    &lt;h1&gt;作業規劃&lt;/h1&gt;
    &lt;p&gt;影片內容&lt;/p&gt;
    &lt;a href="https://www.youtube.com/watch?v=9uq3w6JJS00"&gt;Zero to hero with Python&lt;/a&gt;
&lt;/section&gt;
				</t>
<t tx="ibm.20150918175711.1">&lt;section&gt;
    &lt;h1&gt;Git 操作&lt;/h1&gt;
    &lt;p&gt;git clone&lt;/p&gt;
    &lt;p&gt;git config --global user.name&lt;/p&gt;
    &lt;p&gt;git config --global user.email&lt;/p&gt;
    &lt;p&gt;git add -A&lt;/p&gt;
    &lt;p&gt;git commit -m&lt;/p&gt;
    &lt;p&gt;git push&lt;/p&gt;
    &lt;p&gt;git pull&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="ibm.20150918175951.1">&lt;section&gt;
    &lt;h1&gt;Jupyter 操作&lt;/h1&gt;
    &lt;p&gt;啟動&lt;/p&gt;
    &lt;p&gt;基本執行&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="ibm.20150918181528.1">&lt;section&gt;
    &lt;h1&gt;結論&lt;/h1&gt;
    &lt;p&gt;自主開放學習&lt;/p&gt;
    &lt;p&gt;線上教材&lt;/p&gt;
    &lt;p&gt;影音教材&lt;/p&gt;
&lt;/section&gt;</t>
<t tx="leo.20151115135311.1">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;我的作業&lt;/h2&gt;
    &lt;p&gt;第一週&lt;/p&gt;
    &lt;p&gt;2015 / 09 / 17&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151115135951.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151115135951.10">&lt;section&gt;
    &lt;h4&gt;投影片&lt;/h4&gt;
    &lt;p&gt;成績自評分數&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151115135951.11">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151115135951.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151115135951.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151115135951.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151115135951.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151115135951.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151115135951.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;各週作業進度&lt;/h1&gt;
    &lt;p&gt;第 1 ~ 8 週&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151115135951.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;資料統整&lt;/h2&gt;
    &lt;p&gt;w1 ~ w9&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151115135951.9">&lt;section id="hw-task-one"&gt;
    &lt;h3&gt;作業任務&lt;/h3&gt;
    &lt;p&gt;作業任務的統整&lt;/p&gt;
&lt;/section&gt;
				
</t>
<t tx="leo.20151115223816.1">&lt;section id="hw-task-one"&gt;
    &lt;h2 align="left"&gt;第一週筆記&lt;/h2&gt;
    &lt;p align="left"&gt;1.下載“ Ana3_2015 ”檔案。&lt;/p&gt;
    
    &lt;p align="left"&gt;2.登入課程網址，閱讀課程相關文章。&lt;/p&gt;
   
    &lt;p align="left"&gt;3.說明課程內容及任務。&lt;/p&gt;
    
    &lt;p align="left"&gt;4.點選文章中的 reveal.js 倉儲： https://github.com/coursemdetw/reveal &lt;/p&gt;

    &lt;p align="left"&gt;5.嘗試在近端與遠端上輸出字串 。&lt;/p&gt;
    
    &lt;p align="left"&gt;6.建立個人 Github 課程倉儲 ，並命名為 2015cadp。&lt;/p&gt;
   
    &lt;p align="left"&gt;7.學習如何於近端 (cmd) 創建 " Github " 的分支(gh-pages)，再推送至遠端 (Github) 。&lt;/p&gt;
    
    &lt;p align="left"&gt;8.輸入 "192.168.1.35:8000 "，下載資料。&lt;/p&gt;
   
&lt;/section&gt;


</t>
<t tx="leo.20151115224848.1">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;結論&lt;/h2&gt;
        &lt;p&gt;1.心得&lt;/p&gt;
        &lt;p&gt;2.自評&lt;/p&gt;
        &lt;p&gt;3.啟發&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;心得&lt;/h2&gt;
        &lt;p&gt;這週任務是懂非懂，雖然有上課筆記與教學影片提供參考，但實際操作還是有問題，例如：可創建倉儲，卻無法顯示網頁(指〝.html〞)，經過查證後，並非操作流程錯誤，而是倉儲認證未通過，結論，只要認證通過就能成功，經過這次的經歷，真的讓我印象深刻，也從中吸收到新的知識，更讓我領悟出一些道理呢！&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自評&lt;/h2&gt;
        &lt;p&gt;90 分&lt;/p&gt;
    &lt;/section&gt;    
    &lt;section&gt;
        &lt;h2&gt;啟發&lt;/h2&gt;
        &lt;p&gt;失敗為成功之母&lt;/p&gt;         
    &lt;/section&gt;
&lt;/section&gt;			
				
</t>
<t tx="leo.20151115232422.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151115232422.10">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務二&lt;/h2&gt;
        &lt;p&gt;1.任務說明&lt;/p&gt;
        &lt;p&gt;2.參考網址&lt;/p&gt;
        &lt;p&gt;3.參考影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2 align="left"&gt;任務說明&lt;/h2&gt;
        &lt;p align="left"&gt; (1)安裝 leo - editor 。&lt;/p&gt;
        &lt;p align="left"&gt; (2)修改內部資料。&lt;/p&gt;
        &lt;p align="left"&gt;(3)完成w1進度。&lt;/p&gt;
        &lt;p align="left"&gt;(4)新增`個人`倉儲內容。&lt;/p&gt;
        &lt;p align="left"&gt;(5)下載課程影片。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考網址&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt;&lt;a href=" http://wordpress-2015course.rhcloud.com/?p=3641"&gt;w2&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考影片&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/139886319"&gt;Vimeo - W2 - 1&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/139890840"&gt;Vimeo - W2 - 2&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/139892322"&gt;Vimeo - W2 - 3&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/139893872"&gt;Vimeo - W2 - 4&lt;/a&gt;&lt;/p&gt;
        &lt;/section&gt;
&lt;/section&gt;

   
  
    


 






		
				
</t>
<t tx="leo.20151115232422.11">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務成果&lt;/h2&gt;
        &lt;p&gt;1.倉儲網址&lt;/p&gt;
        &lt;p&gt;2.網頁網址&lt;/p&gt;
        &lt;p&gt;3.自製影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;倉儲網址&lt;/h2&gt;
        &lt;p&gt;&lt;a href="https://github.com/40323107/2015fallcadpa/tree/gh-pages"&gt;40323107 - Github&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;網頁網址&lt;/h2&gt;
        &lt;p&gt;&lt;a href="http://40323107.github.io/2015fallcadpa/"&gt;40323107 -  Pages&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自製影片&lt;/h2&gt;
        &lt;p&gt;1.如何安裝leo編輯器&lt;/p&gt;
        &lt;p&gt;2.如何新增倉儲內容&lt;/p&gt;
        &lt;p&gt;3.如何下載課程影片&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;		
</t>
<t tx="leo.20151115232422.12">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;結論&lt;/h2&gt;
        &lt;p&gt;1.心得&lt;/p&gt;
        &lt;p&gt;2.自評&lt;/p&gt;
        &lt;p&gt;3.啟發&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;心得&lt;/h2&gt;
        &lt;p&gt;這週是接續上週的任務內容，教導(解決)我們如何創建倉儲與安裝 leo，新的任務則是增加倉儲內容，結論，當我們完成這週任務的時候，必須要有個人Github倉儲、個人網頁、投影片...等，總之，整體而言，都能理解，只是還需要多研究與操作，理清思緒就行了，其實沒有很困難，是我們想太多、搞太複雜、做太少而已。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自評&lt;/h2&gt;
        &lt;p&gt;88 分&lt;/p&gt;
    &lt;/section&gt;    
    &lt;section&gt;
        &lt;h2&gt;啟發&lt;/h2&gt;
        &lt;p&gt;「知識」是別人所贈與的，「經驗」是自己所擁有的。&lt;/p&gt;         
    &lt;/section&gt;
&lt;/section&gt;			
				
</t>
<t tx="leo.20151115232422.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151115232422.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151115232422.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151115232422.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151115232422.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151115232422.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151115232422.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;我的作業&lt;/h2&gt;
    &lt;p&gt;第二週&lt;/p&gt;
    &lt;p&gt;2015 / 09 / 24&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151115232422.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;四設計二甲&lt;/h2&gt;
    &lt;p&gt;40323107&lt;/p&gt;
    &lt;p&gt;廖佑珊&lt;/p&gt;		
&lt;/section&gt;

	
</t>
<t tx="leo.20151115232422.9">&lt;section id="hw-task-one"&gt;
    &lt;h2 align="left"&gt;第二週筆記&lt;/h2&gt;
    &lt;p align="left"&gt;1.說明課程內容及任務。&lt;/p&gt;
    &lt;p align="left"&gt;2.說明如何安裝 `leo`。&lt;/p&gt;
    &lt;p align="left"&gt;3.說明 `git clone` 與 `download` 的差異。&lt;/p&gt;
    &lt;p align="left"&gt;4.檢查 launchLeo.py。&lt;/p&gt;
    &lt;p align="left"&gt;5.創建新倉儲。&lt;/p&gt;
    &lt;p align="left"&gt;6.下載老師的`reveal.js` 倉儲。&lt;/p&gt;
    &lt;p align="left"&gt;7.複製`reveal.js倉儲`的`內容`至`自己`的倉儲。&lt;/p&gt;
    &lt;p align="left"&gt;8.下載課程影片。&lt;/p&gt;
&lt;/section&gt;






















				
</t>
<t tx="leo.20151115232433.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151115232433.10">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務三&lt;/h2&gt;
        &lt;p&gt;1.任務說明&lt;/p&gt;
        &lt;p&gt;2.參考網址&lt;/p&gt;
        &lt;p&gt;3.參考影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2 align="left"&gt;任務說明&lt;/h2&gt;
        &lt;p align="left"&gt;(1)下載 fix 與 reveal-gh-pages 的檔案。&lt;/p&gt;
        &lt;p align="left"&gt;(2)新增個人網頁與投影片。&lt;/p&gt;
        &lt;p align="left"&gt;(3)編輯個人投影片。&lt;/p&gt;
        &lt;p align="left"&gt;(4)修改 notebook.py 。&lt;/p&gt;
        &lt;p align="left"&gt;(5)下載 solvespace 軟體與閱讀說明書。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考網址&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt; &lt;a href="http://wordpress-2015course.rhcloud.com/?p=3650"&gt;w3&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt; &lt;a href="http://wordpress-2015course.rhcloud.com/?p=4054"&gt;notebook&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt; &lt;a href="http://wordpress-2015course.rhcloud.com/?p=3971"&gt;Solvespace&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考影片&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/141021392"&gt;Vimeo - W3 - 1&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/141024439"&gt;Vimeo - W3 - 2&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/141026116"&gt;Vimeo - W3 - 3&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;


 




			
				
</t>
<t tx="leo.20151115232433.11">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務成果&lt;/h2&gt;
        &lt;p&gt;1.倉儲網址&lt;/p&gt;
        &lt;p&gt;2.網頁網址&lt;/p&gt;
        &lt;p&gt;3.自製影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;倉儲網址&lt;/h2&gt;
        &lt;p&gt;&lt;a href="https://github.com/40323107/2015fallcadpa/tree/gh-pages"&gt;40323107 - Github&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
        &lt;section&gt;
        &lt;h2&gt;網頁網址&lt;/h2&gt;
        &lt;p&gt;&lt;a href="http://40323107.github.io/2015fallcadpa/"&gt;40323107 -  Pages&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自製影片&lt;/h2&gt;
        &lt;p&gt;1.如何下載相關檔案&lt;/p&gt;
        &lt;p&gt;2.如何新增網頁與投影片&lt;/p&gt;
        &lt;/section&gt;
&lt;/section&gt;

	
</t>
<t tx="leo.20151115232433.12">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;結論&lt;/h2&gt;
        &lt;p&gt;1.心得&lt;/p&gt;
        &lt;p&gt;2.自評&lt;/p&gt;
        &lt;p&gt;3.啟發&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;心得&lt;/h2&gt;
        &lt;p&gt;這週獲得好多知識喔！如：新增網頁與投影片、編輯投影片格式...等，也學到新的軟體 solvespace 呢！solvespace整體架構有點像 Auto CAD，可惜的是 英文版 的，還有，操作方式也不太一樣，總之，好像有難度，所以還需要研究與理解，另外，編輯自己的投影片就是改變格式(可上下左右翻閱)，超有趣的，總之，獲益良多。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自評&lt;/h2&gt;
        &lt;p&gt;88 分&lt;/p&gt;
    &lt;/section&gt;    
    &lt;section&gt;
        &lt;h2&gt;啟發&lt;/h2&gt;
        &lt;p&gt;學以致用&lt;/p&gt; 
        &lt;p&gt;凡事都要積極的嘗試&lt;/p&gt;        
    &lt;/section&gt;
&lt;/section&gt;

			
				
</t>
<t tx="leo.20151115232433.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151115232433.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151115232433.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151115232433.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151115232433.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151115232433.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151115232433.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;我的作業&lt;/h2&gt;
    &lt;p&gt;第三週&lt;/p&gt;
    &lt;p&gt;2015 / 10 / 01&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151115232433.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;四設計二甲&lt;/h2&gt;
    &lt;p&gt;40323107&lt;/p&gt;
    &lt;p&gt;廖佑珊&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151115232433.9">&lt;section id="hw-task-one"&gt;
    &lt;h2 align="left"&gt;第三週筆記&lt;/h2&gt;
    &lt;p align="left"&gt;1.說明課程內容及任務。&lt;/p&gt;
    &lt;p align="left"&gt;2.說明 科學與工程的差異。&lt;/p&gt;
    &lt;p align="left"&gt;3.下載 fix 與 reveal - gh-pages 檔案。&lt;/p&gt;
    &lt;p align="left"&gt;4.說明如何新增網頁與投影片。&lt;/p&gt;
    &lt;p align="left"&gt;5.說明如何編輯個人投影片。&lt;/p&gt;
    &lt;p align="left"&gt;6.說明 notebook.py 文章與如何修改 。&lt;/p&gt;
    &lt;p align="left"&gt;7.說明 solvespace 文章與基本操作。&lt;/p&gt;
    &lt;p align="left"&gt;8.下載 solvespace 軟體。&lt;/p&gt;
    &lt;p align="left"&gt;9.說明如何利用 git 指令刪除檔案。&lt;/p&gt;
    &lt;p align="left"&gt;10.下載課程教學影片。&lt;/p&gt;

&lt;/section&gt;















				
</t>
<t tx="leo.20151115232441.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151115232441.10">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務四&lt;/h2&gt;
        &lt;p&gt;1.任務說明&lt;/p&gt;
        &lt;p&gt;2.參考網址&lt;/p&gt;
        &lt;p&gt;3.參考影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2 align="left"&gt;任務說明&lt;/h2&gt;
        &lt;p align="left"&gt;(1)下載 solvespace 2.1版。&lt;/p&gt;
        &lt;p align="left"&gt;(2)利用 solvespace 繪圖。&lt;/p&gt;
        &lt;p align="left"&gt;(3)閱讀相關文章。( ※Ipthon、Jupyter、solvespace) &lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考網址&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt;&lt;a href="http://wordpress-2015course.rhcloud.com/?p=3657"&gt;w4&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="http://wordpress-2015course.rhcloud.com/?p=3971"&gt;Solvespace&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考影片&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/141762531"&gt;Vimeo - W4 - 1&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/141370058"&gt;Vimeo - W4 - 2&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;





 


			
				
</t>
<t tx="leo.20151115232441.11">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務成果&lt;/h2&gt;
        &lt;p&gt;1.零件圖片&lt;/p&gt;
        &lt;p&gt;2.自製影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;零件圖片&lt;/h2&gt;
        &lt;p&gt;40323107 images&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自製影片&lt;/h2&gt;
        &lt;p&gt;solvespace film&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;

	
</t>
<t tx="leo.20151115232441.12">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;結論&lt;/h2&gt;
        &lt;p&gt;1.心得&lt;/p&gt;
        &lt;p&gt;2.自評&lt;/p&gt;
        &lt;p&gt;3.啟發&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;心得&lt;/h2&gt;
        &lt;p&gt;這週主要任務是利用 solvespace 繪製零件，一開始認為很簡單，結果慘不忍賭呢！還好有老師的現場教學才能順利完成任務，看來這次是把事情簡單化了，總之，經過教授的解說，至少知道 solvespace 的基本指令與操作，其他部分就要靠自己去理解與摸索了，經過這次教學，讓我深刻的領悟到英文真的很重要啊！&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自評&lt;/h2&gt;
        &lt;p&gt;85分&lt;/p&gt;
    &lt;/section&gt;    
    &lt;section&gt;
        &lt;h2&gt;啟發&lt;/h2&gt;
        &lt;p&gt;學習要專注&lt;/p&gt;    
        &lt;p&gt;學習要持之以恆&lt;/p&gt;
        &lt;p&gt;英文能力很重要&lt;/p&gt;         
    &lt;/section&gt;
&lt;/section&gt;			
				
</t>
<t tx="leo.20151115232441.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151115232441.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151115232441.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151115232441.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151115232441.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151115232441.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151115232441.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;我的作業&lt;/h2&gt;
    &lt;p&gt;第四週&lt;/p&gt;
    &lt;p&gt;2015 / 10 / 08&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151115232441.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;四設計二甲&lt;/h2&gt;
    &lt;p&gt;40323107&lt;/p&gt;
    &lt;p&gt;廖佑珊&lt;/p&gt;	
&lt;/section&gt;
	
</t>
<t tx="leo.20151115232441.9">&lt;section id="hw-task-one"&gt;
    &lt;h2 align="left"&gt;第四週筆記&lt;/h2&gt;
    &lt;p align="left"&gt;1.說明課程內容及任務。&lt;/p&gt;
    &lt;p align="left"&gt;2.說明 Ipthon 與 Jupyter 的差異。&lt;/p&gt;
    &lt;p align="left"&gt;3.說明變頻的原理。&lt;/p&gt;
    &lt;p align="left"&gt;4.說明如何下載 solvespace 2.1版 ，並繪圖。&lt;/p&gt;
    &lt;p align="left"&gt;5.利用 solvespace 繪圖。(※學生)&lt;/p&gt;
    &lt;p align="left"&gt;6.solvespace 繪圖教學。(※教授)&lt;/p&gt;
    &lt;p align="left"&gt;7.提供學習語言的優先順序。&lt;/p&gt;
&lt;/section&gt;













				
</t>
<t tx="leo.20151115232449.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151115232449.10">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務五&lt;/h2&gt;
        &lt;p&gt;1.任務說明&lt;/p&gt;
        &lt;p&gt;2.參考網址&lt;/p&gt;
        &lt;p&gt;3.參考影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2 align="left"&gt;任務說明&lt;/h2&gt;
        &lt;p align="left"&gt;(1)下載 reveal2-gh-pages 與 fix。&lt;/p&gt;
        &lt;p align="left"&gt;(2)個人網頁改版。&lt;/p&gt;
        &lt;p align="left"&gt;(3)閱讀相關文章。 ( ※Creo Parametric ) &lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考網址&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt; &lt;a href="http://wordpress-2015course.rhcloud.com/?p=3660"&gt;w5&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt; &lt;a href="http://wordpress-2015course.rhcloud.com/?p=4146"&gt;Creo Parametric&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt; &lt;a href="http://wordpress-2015course.rhcloud.com/?p=4148"&gt;作業自評取分重點&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考影片&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/142093273"&gt;Vimeo - W5 - 1&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/142093479"&gt;Vimeo - W5 - 2&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/142098889"&gt;Vimeo - W5 - 3&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;





		
				
</t>
<t tx="leo.20151115232449.11">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務成果&lt;/h2&gt;
        &lt;p&gt;1.網頁網址&lt;/p&gt;
        &lt;p&gt;2.自製影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;網頁網址&lt;/h2&gt;
        &lt;p&gt;&lt;a href="http://40323107.github.io/2015cadpw1/"&gt;40323107 -  Pages - old&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="http://40323107.github.io/2015fallcadpa/"&gt;40323107 -  Pages - new&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自製影片&lt;/h2&gt;
        &lt;p&gt;1.如何改版&lt;/p&gt;
        &lt;p&gt;2.刪除檔案&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;

	
</t>
<t tx="leo.20151115232449.12">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;結論&lt;/h2&gt;
        &lt;p&gt;1.心得&lt;/p&gt;
        &lt;p&gt;2.自評&lt;/p&gt;
        &lt;p&gt;3.啟發&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;心得&lt;/h2&gt;
        &lt;p&gt;這週吸收很多資訊呢！腦容量有點承受不住，但我會盡量理解並學以致用的，關於任務，大至上沒問題，很順利的改版成功並新增內容呢！另外，對於利用 git 指令刪除檔案，有點懂又不太懂，就是盡量做到〝只增不刪〞就不會產生大問題了，還有關於 Creo Parametric 基本操作，還在理解中，但整體架構跟 SolidWorks 軟體很像呢！就是不知道操作模式是否雷同，反正〝試〞就對了，總之，整體而言，還可以，有問題我會請教同學與教授的。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自評&lt;/h2&gt;
        &lt;p&gt;80 分&lt;/p&gt;
    &lt;/section&gt;    
    &lt;section&gt;
        &lt;h2&gt;啟發&lt;/h2&gt;
        &lt;p&gt;遇到問題要勇敢面對&lt;/p&gt;
        &lt;p&gt;你的成功是建構在別人的失敗上&lt;/p&gt;
        &lt;p&gt;凡事都要大膽嘗試，才能從中得到答案&lt;/p&gt;         
    &lt;/section&gt;
&lt;/section&gt;			
				
</t>
<t tx="leo.20151115232449.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151115232449.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151115232449.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151115232449.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151115232449.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151115232449.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151115232449.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;我的作業&lt;/h2&gt;
    &lt;p&gt;第五週&lt;/p&gt;
    &lt;p&gt;2015 / 10 / 15&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151115232449.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;四設計二甲&lt;/h2&gt;
    &lt;p&gt;40323107&lt;/p&gt;
    &lt;p&gt;廖佑珊&lt;/p&gt;	
&lt;/section&gt;
	
</t>
<t tx="leo.20151115232449.9">&lt;section id="hw-task-one"&gt;
    &lt;h2 align="left"&gt;第五週筆記&lt;/h2&gt;
    &lt;p align="left"&gt;1.說明課程內容及任務。&lt;/p&gt;
    &lt;p align="left"&gt;2.說明〝如何從作業自評中取分〞這篇文章。&lt;/p&gt;
    &lt;p align="left"&gt;3.說明 Creo Parametric 基本操作。&lt;/p&gt;
    &lt;p align="left"&gt;4.說明如何將個人網頁做改版。&lt;/p&gt;
    &lt;p align="left"&gt;5.說明如何利用 git rm 刪除網頁。&lt;/p&gt;
    &lt;p align="left"&gt;6.說明何謂〝對等生產模式〞。&lt;/p&gt;
    &lt;p align="left"&gt;7.影片觀賞。&lt;/p&gt;
    &lt;p align="left"&gt;8.下載 reveal2-gh-pages 倉儲 與  fix 檔案。&lt;/p&gt;
&lt;/section&gt;






				
</t>
<t tx="leo.20151115232457.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151115232457.10">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務六&lt;/h2&gt;
        &lt;p&gt;1.任務說明&lt;/p&gt;
        &lt;p&gt;2.參考網址&lt;/p&gt;
        &lt;p&gt;3.參考影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2 align="left"&gt;任務說明&lt;/h2&gt;
        &lt;p align="left"&gt;(1)閱讀 Creo Parametric 基本操作。&lt;/p&gt;
        &lt;p align="left"&gt;(2)將自己加入全班協同倉儲中。&lt;/p&gt;
        &lt;p align="left"&gt;(3)於全班協同倉儲中新增自己的倉儲。&lt;/p&gt;
        &lt;p align="left"&gt;(4)產生全班協同倉儲的個人網頁。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考網址&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt;&lt;a href="http://wordpress-2015course.rhcloud.com/?p=3664"&gt;w6&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="http://wordpress-2015course.rhcloud.com/?p=4146"&gt;Creo Parametric&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://github.com/2015fallhw/2015fallcadpa/tree/gh-pages"&gt;全班協同倉儲&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="http://2015fallhw.github.io/2015fallcadpa/"&gt;全班協同網頁&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考影片&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/143225578"&gt;Vimeo - W6 - 1&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
 &lt;/section&gt;
 




			
				
</t>
<t tx="leo.20151115232457.11">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務成果&lt;/h2&gt;
        &lt;p&gt;1.網頁網址&lt;/p&gt;
        &lt;p&gt;2.自製影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;網頁網址&lt;/h2&gt;
        &lt;p&gt;&lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323107/"&gt;40323107 - class pages&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自製影片&lt;/h2&gt;
        &lt;p&gt;創建全班協同倉儲的個人倉儲與網頁&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;		
</t>
<t tx="leo.20151115232457.12">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;結論&lt;/h2&gt;
        &lt;p&gt;1.心得&lt;/p&gt;
        &lt;p&gt;2.自評&lt;/p&gt;
        &lt;p&gt;3.啟發&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;心得&lt;/h2&gt;
        &lt;p&gt;這週的任務是做全班協同呢！是困難還是簡單，嘗試過後就知道，感覺有點躍躍欲試呢！那我要認真做筆記才行，然後，根據筆記的操作流程，順利的推出去了，也確認網頁建構成功，當下有種難以言喻的雀躍感與成就感呢！成功的瞬間令人心情舒暢呀！,但心中卻有不好的預感，過沒多久，預感成真， leo 掛掉了，是該喜還是該悲呢！後來大家就一起討論，嘗試找出錯誤，因此，從中我吸收到新的知識與方法，感覺錯誤反而讓人學到更多知識，好複雜的情緒唷！另外，因為很快就完成自己的任務，所以嘗試著去幫助別人，從中獲得諸多感受，但可以確認的是幫助別人對自己是有好處的，可以幫助自己快速的理解並加深印象、熟悉流程...等，總之，這一週的表現還不錯。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自評&lt;/h2&gt;
        &lt;p&gt;88 分&lt;/p&gt;
    &lt;/section&gt;    
    &lt;section&gt;
        &lt;h2&gt;啟發&lt;/h2&gt;
        &lt;p&gt;沒問題就是有問題&lt;/p&gt; 
        &lt;p&gt;成功為失敗的開端&lt;/p&gt; 
        &lt;p&gt;凡事都要小心謹慎&lt;/p&gt;
        &lt;p&gt;助人為快樂之本喔&lt;/p&gt;          
    &lt;/section&gt;
&lt;/section&gt;			
				
</t>
<t tx="leo.20151115232457.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151115232457.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151115232457.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151115232457.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151115232457.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151115232457.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151115232457.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;我的作業&lt;/h2&gt;
    &lt;p&gt;第六週&lt;/p&gt;
    &lt;p&gt;2015 / 10 / 22&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151115232457.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;四設計二甲&lt;/h2&gt;
    &lt;p&gt;40323107&lt;/p&gt;
    &lt;p&gt;廖佑珊&lt;/p&gt;
&lt;/section&gt;
	
</t>
<t tx="leo.20151115232457.9">&lt;section id="hw-task-one"&gt;
    &lt;h2 align="left"&gt;第六週筆記&lt;/h2&gt;
    &lt;p align="left"&gt;1.說明課程內容及任務。&lt;/p&gt;
    &lt;p align="left"&gt;2.說明 Creo Parametric 基本操作。&lt;/p&gt;
    &lt;p align="left"&gt;3.說明如何全班協同。&lt;/p&gt;
    &lt;p align="left"&gt;4.說明如何於全班協同倉儲新增自己的倉儲。&lt;/p&gt;
    &lt;p align="left"&gt;5.製作全班協同的個人網頁。&lt;/p&gt;
    &lt;p align="left"&gt;6.下載  fix.zip 。&lt;/p&gt;
&lt;/section&gt;




				
</t>
<t tx="leo.20151115232505.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151115232505.10">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務七&lt;/h2&gt;
        &lt;p&gt;1.任務說明&lt;/p&gt;
        &lt;p&gt;2.參考網址&lt;/p&gt;
        &lt;p&gt;3.參考影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2 align="left"&gt;任務說明&lt;/h2&gt;
        &lt;p align="left"&gt;(1)閱讀 Creo Parametric 基本操作。 &lt;/p&gt;
        &lt;p align="left"&gt;(2)下載 2015fallcadpa-gh-pages 倉儲。&lt;/p&gt;
        &lt;p align="left"&gt;(3)編輯全班協同的個人網頁內容。&lt;/p&gt;
        &lt;p align="left"&gt;(4)學習如何解決衝突。&lt;/p&gt;
        &lt;p align="left"&gt;(5)學習分析衝突架構。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考網址&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt;&lt;a href="http://wordpress-2015course.rhcloud.com/?p=3667"&gt;w7&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt; &lt;a href="https://github.com/2015fallhw/2015fallcadpa/tree/gh-pages"&gt;全班協同倉儲&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考影片&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/143572506"&gt;Vimeo - W7 - 1&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/143574887"&gt;Vimeo - W7 - 2&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/143963816"&gt;Vimeo - W7 - 3&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;



				
</t>
<t tx="leo.20151115232505.11">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務成果&lt;/h2&gt;
        &lt;p&gt;1.倉儲網址&lt;/p&gt;
        &lt;p&gt;2.網頁網址&lt;/p&gt;
        &lt;p&gt;3.自製影片&lt;/p&gt;
    &lt;/section&gt;
        &lt;section&gt;
        &lt;h2&gt;倉儲網址&lt;/h2&gt;
         &lt;p&gt; &lt;a href="https://github.com/2015fallhw/2015fallcadpa/tree/gh-pages"&gt;全班協同倉儲&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;網頁網址&lt;/h2&gt;
        &lt;p&gt;&lt;a href="http://2015fallhw.github.io/2015fallcadpa/user/40323107/"&gt;40323107 - class pages&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自製影片&lt;/h2&gt;
        &lt;p&gt;1.新增資料&lt;/p&gt;
        &lt;p&gt;2.修改衝突&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;		
</t>
<t tx="leo.20151115232505.12">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;結論&lt;/h2&gt;
        &lt;p&gt;1.心得&lt;/p&gt;
        &lt;p&gt;2.自評&lt;/p&gt;
        &lt;p&gt;3.啟發&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;心得&lt;/h2&gt;
        &lt;p&gt;這週的任務是接續上週的問題，因此，課程內容差不多，只是多一點點問題罷了，所以，這週主要是教導我們如何解決衝突與認識衝突架構，就是因為這個步驟很容易被忽略掉，而導致連鎖效應，因此，經過上週的教訓與經歷，告訴我別輕視這個問題，很重要、很關鍵呀！所以我得學起來、記下來，避免再犯相同的錯.才行，其餘部份問題比較少、不嚴重，還能夠自我處理，總之，就是不斷的學習、不斷的吸收、彙整資料...等。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自評&lt;/h2&gt;
        &lt;p&gt;85 分&lt;/p&gt;
    &lt;/section&gt;    
    &lt;section&gt;
        &lt;h2&gt;啟發&lt;/h2&gt;
        &lt;p&gt;相信第六感，很準的&lt;/p&gt; 
        &lt;p&gt;知錯能改，善莫大焉&lt;/p&gt;        
    &lt;/section&gt;
&lt;/section&gt;			
				
</t>
<t tx="leo.20151115232505.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151115232505.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151115232505.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151115232505.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151115232505.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151115232505.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151115232505.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;我的作業&lt;/h2&gt;
    &lt;p&gt;第七週&lt;/p&gt;
    &lt;p&gt;2015 / 10 / 29&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151115232505.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;四設計二甲&lt;/h2&gt;
    &lt;p&gt;40323107&lt;/p&gt;
    &lt;p&gt;廖佑珊&lt;/p&gt;	
&lt;/section&gt;
	
</t>
<t tx="leo.20151115232505.9">&lt;section id="hw-task-one"&gt;
    &lt;h2 align="left"&gt;第七週筆記&lt;/h2&gt;
    &lt;p align="left"&gt;1.說明課程內容及任務。&lt;/p&gt;
    &lt;p align="left"&gt;2.說明如何解決衝突與衝突的架構。&lt;/p&gt;
    &lt;p align="left"&gt;3.說明 Creo Parametric 基本操作。&lt;/p&gt;
    &lt;p align="left"&gt;4.說明如何同時運作個人與全班的倉儲修改。&lt;/p&gt;
&lt;/section&gt;




				
</t>
<t tx="leo.20151115232511.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151115232511.10">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務八&lt;/h2&gt;
        &lt;p&gt;1.任務說明&lt;/p&gt;
        &lt;p&gt;2.參考網址&lt;/p&gt;
        &lt;p&gt;3.參考影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2 align="left"&gt;任務說明&lt;/h2&gt;
        &lt;p align="left"&gt; (1)資料統整。( ※第 1 ~ 8 週 )&lt;/p&gt;
        &lt;p align="left"&gt;(2)全班協同網頁與個人網頁的連結。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考網址&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt;&lt;a href="http://wordpress-2015course.rhcloud.com/?p=3670"&gt;w8&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考影片&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://vimeo.com/user24079973/videos"&gt;Vimeo - W8&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;


			
				
</t>
<t tx="leo.20151115232511.11">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務成果&lt;/h2&gt;
        &lt;p&gt;1.網頁與倉儲網址&lt;/p&gt;
        &lt;p&gt;2.自製教學影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;網頁與倉儲網址&lt;/h2&gt;
         &lt;p&gt;&lt;a href="http://40323107.github.io/2015fallcadpa/"&gt;40323107 -  Pages&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://github.com/40323107/2015fallcadpa/tree/gh-pages"&gt;40323107 - Github&lt;/a&gt;&lt;/p&gt;
         &lt;p&gt;&lt;a href="href="http://2015fallhw.github.io/2015fallcadpa/user/40323107/"&gt;40323107 - Class Pages&lt;/a&gt;&lt;/p&gt;
         &lt;p&gt;&lt;a href="href="https://github.com/2015fallhw/2015fallcadpa/tree/gh-pages"&gt;Class Github&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自製影片&lt;/h2&gt;
        &lt;p&gt;全班與個人網頁連結&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;		





        
      
       </t>
<t tx="leo.20151115232511.12">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;結論&lt;/h2&gt;
        &lt;p&gt;1.心得&lt;/p&gt;
        &lt;p&gt;2.自評&lt;/p&gt;
        &lt;p&gt;3.啟發&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;心得&lt;/h2&gt;
        &lt;p&gt;這週任務並不難，只是系統容易出錯，導致進度有些阻礙而已，大致上沒問題，還能夠教導別人呢！但還是有新的知識要學，雖然一開始不太懂，但詢問過同學與教授加上自我嘗試後，我理解了，總之，雖然思緒待整理，但感覺很有趣、很有成就感。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自評&lt;/h2&gt;
        &lt;p&gt;85 分&lt;/p&gt;
    &lt;/section&gt;    
    &lt;section&gt;
        &lt;h2&gt;啟發&lt;/h2&gt;
        &lt;p&gt;凡事都要小心謹慎&lt;/p&gt; 
        &lt;p&gt;從討論中獲得答案&lt;/p&gt;        
    &lt;/section&gt;
&lt;/section&gt;			
				
</t>
<t tx="leo.20151115232511.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151115232511.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151115232511.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151115232511.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151115232511.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151115232511.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151115232511.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;我的作業&lt;/h2&gt;
    &lt;p&gt;第八週&lt;/p&gt;
    &lt;p&gt;2015 / 11 / 05&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151115232511.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;四設計二甲&lt;/h2&gt;
    &lt;p&gt;40323107&lt;/p&gt;
    &lt;p&gt;廖佑珊&lt;/p&gt;	
&lt;/section&gt;
	
</t>
<t tx="leo.20151115232511.9">&lt;section id="hw-task-one"&gt;
    &lt;h2 align="left"&gt;第八週筆記&lt;/h2&gt;
    &lt;p align="left"&gt;1.說明課程內容及任務。&lt;/p&gt;
    &lt;p align="left"&gt;2.說明如何將全班協同與個人網誌做連結。&lt;/p&gt;
    &lt;p align="left"&gt;3.說明期中評分規則。&lt;/p&gt;
    &lt;p align="left"&gt;4.將 W1 ~ W8 的作業做統整。&lt;/p&gt;
    &lt;p align="left"&gt;5.說明 Creo Parametric 基本操作。&lt;/p&gt;
&lt;/section&gt;












				
</t>
<t tx="leo.20151115232520.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151115232520.10">&lt;section&gt;
    &lt;section&gt;
        &lt;h1&gt;任務九&lt;/h1&gt;
        &lt;p&gt;1.任務說明&lt;/p&gt;
        &lt;p&gt;2.參考網址&lt;/p&gt;
        &lt;p&gt;3.參考影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2 align="left"&gt;任務說明&lt;/h2&gt;
        &lt;p align="left"&gt;(1) CADPA 登錄自評成績 。&lt;/p&gt;
        &lt;p align="left"&gt;(2)CADPA 登錄網頁網址。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;參考網址&lt;/h3&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt;&lt;a href="http://wordpress-2015course.rhcloud.com/?p=3673"&gt;w9&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="
http://wordpress-2015course.rhcloud.com/?p=4334"&gt;期中報告&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h4&gt;參考影片&lt;/h4&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://vimeo.com/user24079973/videos"&gt;Vimeo - W9&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;			
				
</t>
<t tx="leo.20151115232520.11">&lt;section&gt;
    &lt;section&gt;
        &lt;h1&gt;任務成果&lt;/h1&gt;
        &lt;p&gt;1.倉儲網址&lt;/p&gt;
        &lt;p&gt;2.自製影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;網頁與倉儲網址&lt;/h2&gt;
         &lt;p&gt;&lt;a href="http://40323107.github.io/2015fallcadpa/"&gt;40323107 -  Pages&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://github.com/40323107/2015fallcadpa/tree/gh-pages"&gt;40323107 - Github&lt;/a&gt;&lt;/p&gt;
         &lt;p&gt;&lt;a href="href="http://2015fallhw.github.io/2015fallcadpa/user/40323107/"&gt;40323107 - Class Pages&lt;/a&gt;&lt;/p&gt;
         &lt;p&gt;&lt;a href="href="https://github.com/2015fallhw/2015fallcadpa/tree/gh-pages"&gt;Class Github&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;自製影片&lt;/h3&gt;
        &lt;p&gt;請參考 W1 - W8 &lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;		
</t>
<t tx="leo.20151115232520.12">&lt;section&gt;
    &lt;section&gt;
        &lt;h1&gt;結論&lt;/h1&gt;
        &lt;p&gt;1.心得&lt;/p&gt;
        &lt;p&gt;2.自評&lt;/p&gt;
        &lt;p&gt;3.啟發&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;心得&lt;/h2&gt;
        &lt;p&gt;這週是第九週喔！主要任務為統整 W1 ~ W8 的作業內容，因此，我會將各週內容簡略敘述統整於這週網頁上，而這個投影片則是用來測試與區分文字大小的差異性喔！但我也會針對第九週內容稍做解釋，以方便之後的進度確認，總之，就是資料統整啦！&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;自評&lt;/h3&gt;
        &lt;p&gt;90 分&lt;/p&gt;
    &lt;/section&gt;    
    &lt;section&gt;
        &lt;h4&gt;啟發&lt;/h4&gt;
        &lt;p&gt;做人要誠實&lt;/p&gt;
        &lt;p&gt;船到橋頭自然直&lt;/p&gt; 
        &lt;p&gt;人生結果才是一切&lt;/p&gt;          
    &lt;/section&gt;
&lt;/section&gt;			
				
</t>
<t tx="leo.20151115232520.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151115232520.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151115232520.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151115232520.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151115232520.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151115232520.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151115232520.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h1&gt;我的作業&lt;/h1&gt;
    &lt;p&gt;第九週&lt;/p&gt;
    &lt;p&gt;本週為〝期中考〞週&lt;/p&gt;
    &lt;p&gt;2015 / 11 / 12&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151115232520.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;四設計二甲&lt;/h2&gt;
    &lt;p&gt;40323107&lt;/p&gt;
    &lt;p&gt;廖佑珊&lt;/p&gt;	
&lt;/section&gt;
	
</t>
<t tx="leo.20151115232520.9">&lt;section id="hw-task-one"&gt;
    &lt;h3 align="left"&gt;第九週筆記&lt;/h3&gt;
    &lt;p align="left"&gt;1.說明課程內容及任務。&lt;/p&gt;
    &lt;p align="left"&gt;2.登錄自評分數。&lt;/p&gt;
    &lt;p align="left"&gt;3.登錄全班協同個人網頁與個人網頁。&lt;/p&gt;
 &lt;/section&gt;
				
</t>
<t tx="leo.20151119132034.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151119132034.10">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務十&lt;/h2&gt;
        &lt;p&gt;1.任務說明&lt;/p&gt;
        &lt;p&gt;2.參考網址&lt;/p&gt;
        &lt;p&gt;3.參考影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2 align="left"&gt;任務說明&lt;/h2&gt;
        &lt;p align="left"&gt;(1)點名簽到。&lt;/p&gt;
        &lt;p align="left"&gt;(2)閱讀課程相關文章。&lt;/p&gt;
        &lt;p align="left"&gt;(3)自行下載檔案，並安裝leo。&lt;/p&gt;
        &lt;p align="left"&gt;(4)利用 Creo Parametric軟體 繪製 Nutcracker 機構。&lt;/p&gt;
        &lt;p align="left"&gt;(5)各組協同完成 Nutcracker 機構。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考網址&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt; &lt;a href="http://wordpress-2015course.rhcloud.com/?p=3675"&gt;w10&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考影片&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt; &lt;a href="https://player.vimeo.com/video/145820006"&gt;Vimeo - W10 - 1&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/145825547"&gt;Vimeo - W10 - 2&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;


</t>
<t tx="leo.20151119132034.11">&lt;section&gt;
    &lt;section&gt;
        &lt;h1&gt;任務成果&lt;/h1&gt;
        &lt;p&gt;1.簽到證明。&lt;/p&gt;
        &lt;p&gt;2.操作步驟。&lt;/p&gt;
        &lt;p&gt;3.零件範例。&lt;/p&gt;
        &lt;p&gt;4.任務分配。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;簽到證明&lt;/h2&gt;
        &lt;p&gt;&lt;img src="https://copy.com/NxT8qrUZ9SZF0J3q"width="550"height="450"&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;操作步驟&lt;/h2&gt;
        &lt;p&gt;&lt;a href="https://github.com/40323107/2015cadpa_g2/blob/gh-pages/40323107/%E4%BF%AE%E6%AD%A3%20fix%EF%BC%8C%E5%AE%89%E8%A3%9D%20leo%E7%9A%84%E6%93%8D%E4%BD%9C%E6%AD%A5%E9%A9%9F.md"&gt;修正 fix，安裝 leo&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;零件範例&lt;/h2&gt;
        &lt;p&gt;&lt;img src="https://copy.com/B4yE3LaSQtJnLeCI"width="550"height="450"&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務分配&lt;/h2&gt;
        &lt;p&gt;&lt;img src="https://copy.com/IoptR4zkPhLK3XwB"width="550"height="450"&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;		
</t>
<t tx="leo.20151119132034.12">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;結論&lt;/h2&gt;
        &lt;p&gt;1.心得&lt;/p&gt;
        &lt;p&gt;2.自評&lt;/p&gt;
        &lt;p&gt;3.啟發&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;心得&lt;/h2&gt;
        &lt;p&gt;由於期中考剛過，因此這週的任務並不困難，主要在說明期末報告的規格，如：分組報告、個人報告...等。還有解釋課程的意義為何、教導如何修改 fix 安裝 leo、分組任務為何...等。還有說明分組後組員必須互相協同利用 Creo Parametric軟體 來完成 Nutcracker 機構，並完成每週的團體報告。另外，特別強調&lt;How to be a star engineer&gt;這篇文章的重要性呢！閱讀完與聆聽完教授的概述後，感覺似懂非懂呢！總之，這週的任務並不困難，只是要理解的資訊很多，需要花點時間來整理思緒而已。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自評&lt;/h2&gt;
        &lt;p&gt;90 分&lt;/p&gt;
    &lt;/section&gt;    
    &lt;section&gt;
        &lt;h2&gt;啟發&lt;/h2&gt;
        &lt;p&gt;不懂就要問、不會就要說、不知就要試&lt;/p&gt;         
    &lt;/section&gt;
&lt;/section&gt;			
				
</t>
<t tx="leo.20151119132034.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151119132034.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151119132034.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151119132034.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151119132034.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151119132034.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151119132034.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;我的報告&lt;/h2&gt;
    &lt;p&gt;第十週&lt;/p&gt;
    &lt;p&gt;2015 / 11 / 19&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151119132034.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;四設計二甲&lt;/h2&gt;
    &lt;p&gt;40323107&lt;/p&gt;
    &lt;p&gt;廖佑珊&lt;/p&gt;			
&lt;/section&gt;
	
</t>
<t tx="leo.20151119132034.9">&lt;section id="hw-task-one"&gt;
    &lt;h2 align="left"&gt;第十週筆記&lt;/h2&gt;
    &lt;p align="left"&gt;1.說明課程內容及任務。&lt;/p&gt;
    &lt;p align="left"&gt;2.閱讀 `How to be a star engineer` 的文章。&lt;/p&gt;
    &lt;p align="left"&gt;3.點名簽到。&lt;/p&gt;
    &lt;p align="left"&gt;4.下載與安裝檔案。&lt;/p&gt;
    &lt;p align="left"&gt;5.利用 `Creo Parametric軟體` 繪製 `Nutcracker 機構`。&lt;/p&gt;
    &lt;p align="left"&gt;6.觀看課程相關教學影片。&lt;/p&gt;
&lt;/section&gt;


</t>
<t tx="leo.20151201235152.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151201235152.10">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務十一&lt;/h2&gt;
        &lt;p&gt;1.任務說明&lt;/p&gt;
        &lt;p&gt;2.參考網址&lt;/p&gt;
        &lt;p&gt;3.參考影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2 align="left"&gt;任務說明&lt;/h2&gt;
        &lt;p align="left"&gt;(1)閱讀課程內容相關資訊。&lt;/p&gt;
        &lt;p align="left"&gt;(2)自行下載 fix檔案，並安裝 leo。&lt;/p&gt;
        &lt;p align="left"&gt;(3)創建組別的 leo。&lt;/p&gt;
        &lt;p align="left"&gt;(4)利用`Creo Parametric軟體`繪製零件。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考網址&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt; &lt;a href="http://wordpress-2015course.rhcloud.com/?p=3678"&gt;w11&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考影片&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/146592105"&gt;Vimeo - W11 - 1&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/146593944"&gt;Vimeo - W11 - 2&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;


    
    
    </t>
<t tx="leo.20151201235152.11">&lt;section&gt;
    &lt;section&gt;
        &lt;h1&gt;任務成果&lt;/h1&gt;
        &lt;p&gt;1.零件5繪製。&lt;/p&gt;
        &lt;p&gt;2.零件6繪製。&lt;/p&gt;
        &lt;p&gt;3.相關網址。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;零件5繪製&lt;/h2&gt;
        &lt;p&gt;(1)零件 2D 草圖。&lt;/p&gt;
        &lt;p&gt;(2)零件 3D 圖。&lt;/p&gt;
        &lt;p&gt;(3)零件繪製影片。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件 2D 草圖&lt;/h3&gt;
        &lt;p&gt;&lt;img src="https://copy.com/p9WOhTy1qDsEMrlm"width="450"height="350"&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件 3D 圖&lt;/h3&gt;
        &lt;p&gt;&lt;script src="https://embed.github.com/view/3d/40323107/2015cadpa_g2/gh-pages/40323107/CYLINDER_5-5.stl"&gt;&lt;/script&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件繪製影片&lt;/h3&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/152468947"&gt;CYLINDER-5&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;零件6繪製&lt;/h2&gt;
        &lt;p&gt;(1)零件 2D 草圖。&lt;/p&gt;
        &lt;p&gt;(2)零件 3D 圖。&lt;/p&gt;
        &lt;p&gt;(3)零件繪製影片。&lt;/p&gt;
    &lt;/section&gt;
        &lt;section&gt;
        &lt;h3&gt;零件 2D 草圖&lt;/h3&gt;
        &lt;p&gt;&lt;img src="https://copy.com/iOMWxA7C7jzBOs0O"width="450"height="350"&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件 3D 圖&lt;/h3&gt;
        &lt;p&gt;&lt;script src="https://embed.github.com/view/3d/40323107/2015cadpa_g2/gh-pages/40323107/HANDLE_6-6.stl"&gt;&lt;/script&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件繪製影片&lt;/h3&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/152470110"&gt;HANDLE-6&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;相關網址&lt;/h2&gt;
        &lt;p&gt;&lt;a href="http://2015fallhw.github.io/2015fallcadpa/category/g2.html"&gt;G2 - Pages&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="http://2015fallhw.github.io/2015fallcadpa/g2_w11_1.html"&gt;G2 - W11  Pages&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://github.com/40323107/2015cadpa_g2/tree/gh-pages"&gt;G2 - Github&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://github.com/40323107/2015cadpa_g2/tree/gh-pages/40323107"&gt;G2 - Github - 40323107&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://www.copy.com/browse/a:dd7adaa;z:copy;b:myfiles"&gt;40323107 - Copy.com&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;		
</t>
<t tx="leo.20151201235152.12">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;結論&lt;/h2&gt;
        &lt;p&gt;1.心得&lt;/p&gt;
        &lt;p&gt;2.自評&lt;/p&gt;
        &lt;p&gt;3.啟發&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;心得&lt;/h2&gt;
        &lt;p&gt;&gt;這週的課程內容是沿用上週所教導的知識，然後再提升點困難度。內容則是在描述新版的投影片格式及運用對照法將A、B兩班的倉儲做比較與說明。關於上述的部分，我還不太能理解，所以我得花時間來研究研究才行。另外，若是按照教授的步驟進行的話，大致上進度還算尚可，卻會產生一些疑問呢！比如：創建組別的專屬 leo 時，就碰到一些障礙，最後還被我誤打誤撞弄成功的，感覺超不可思議的！但還是要利用時間自己摸索或請教其他人才行，不然問題一直擱在心裡也挺難受的，還是早點處理得好。還有，利用 Creo Parametric軟體 繪製零件的挑戰性滿高的，這個障礙也得克服才行。總之，這週的任務我是處於似懂非懂的狀態呢！但對於可以吸收到更多的知識，我還是很開心的，只是要做到學以致用可能需要很久吧！反正，先學習就是了。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自評&lt;/h2&gt;
        &lt;p&gt;85 分&lt;/p&gt;
    &lt;/section&gt;    
    &lt;section&gt;
        &lt;h2&gt;啟發&lt;/h2&gt;
        &lt;p&gt;凡事都是一體兩面呢！&lt;/p&gt;         
    &lt;/section&gt;
&lt;/section&gt;			
				
</t>
<t tx="leo.20151201235152.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151201235152.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151201235152.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151201235152.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151201235152.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151201235152.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151201235152.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;我的報告&lt;/h2&gt;
    &lt;p&gt;第十一週&lt;/p&gt;
    &lt;p&gt;2015 / 11 / 26&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151201235152.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;四設計二甲&lt;/h2&gt;
    &lt;p&gt;40323107&lt;/p&gt;
    &lt;p&gt;廖佑珊&lt;/p&gt;			
&lt;/section&gt;
	
</t>
<t tx="leo.20151201235152.9">&lt;section id="hw-task-one"&gt;
    &lt;h2 align="left"&gt;第十一週筆記&lt;/h2&gt;
    &lt;p align="left"&gt;1.說明課程內容及任務。&lt;/p&gt;
    &lt;p align="left"&gt;2.修改 fix.bat，安裝 leo。&lt;/p&gt;
    &lt;p align="left"&gt;3.修改 start.bat ，指定 Jupyter 的啟動目錄為 tmp。&lt;/p&gt;
    &lt;p align="left"&gt;4.創建組別的 leo。&lt;/p&gt;
    &lt;p align="left"&gt;5.利用 `Creo Parametric軟體` 繪製`Nutcracker 機構`零件。&lt;/p&gt;
&lt;/section&gt;


</t>
<t tx="leo.20151201235202.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151201235202.10">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務十二&lt;/h2&gt;
        &lt;p&gt;1.任務說明&lt;/p&gt;
        &lt;p&gt;2.參考網址&lt;/p&gt;
        &lt;p&gt;3.參考影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2 align="left"&gt;任務說明&lt;/h2&gt;
        &lt;p align="left"&gt;(1)安裝 leo。&lt;/p&gt;
        &lt;p align="left"&gt;(2)閱讀課程內容相關資訊。&lt;/p&gt;
        &lt;p align="left"&gt;(3)指定 Jupyter 的啟動目錄為 tmp。&lt;/p&gt;
        &lt;p align="left"&gt;(4)利用`Creo Parametric軟體`繪製零件。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考網址&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt; &lt;a href="http://wordpress-2015course.rhcloud.com/?p=4474"&gt;w12&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考影片&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/147709308"&gt;Vimeo - W12 - 1&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/147712937"&gt;Vimeo - W12 - 2&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/147276192"&gt;Vimeo - W12 - 3&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/147279887"&gt;Vimeo - W12 - 4&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;

    
    
    
    
</t>
<t tx="leo.20151201235202.11">&lt;section&gt;
    &lt;section&gt;
        &lt;h1&gt;任務成果&lt;/h1&gt;
        &lt;p&gt;1.零件7繪製。&lt;/p&gt;
        &lt;p&gt;2.零件8繪製。&lt;/p&gt;
        &lt;p&gt;3.相關網址。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;零件7繪製&lt;/h2&gt;
        &lt;p&gt;(1)零件 2D 草圖。&lt;/p&gt;
        &lt;p&gt;(2)零件 3D 圖。&lt;/p&gt;
        &lt;p&gt;(3)零件繪製影片。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件 2D 草圖&lt;/h3&gt;
        &lt;p&gt;&lt;img src="https://copy.com/BfjeElFXaQRe97gn"width="450"height="350"&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件 3D 圖&lt;/h3&gt;
        &lt;p&gt;&lt;script src="https://embed.github.com/view/3d/40323107/2015cadpa_g2/gh-pages/40323107/HINGE_7-7.stl"&gt;&lt;/script&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件繪製影片&lt;/h3&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/152470821"&gt;HINGE-7&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;零件8繪製&lt;/h2&gt;
        &lt;p&gt;(1)零件 2D 草圖。&lt;/p&gt;
        &lt;p&gt;(2)零件 3D 圖。&lt;/p&gt;
        &lt;p&gt;(3)零件繪製影片。&lt;/p&gt;
    &lt;/section&gt;
        &lt;section&gt;
        &lt;h3&gt;零件 2D 草圖&lt;/h3&gt;
        &lt;p&gt;&lt;img src="https://copy.com/ngfUdrXkskTKIfZD"width="450"height="350"&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件 3D 圖&lt;/h3&gt;
        &lt;p&gt;&lt;script src="https://embed.github.com/view/3d/40323107/2015cadpa_g2/gh-pages/40323107/PISTON_8-8.stl"&gt;&lt;/script&gt;&lt;/script&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件繪製影片&lt;/h3&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/152471254"&gt;PISTON-8&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;相關網址&lt;/h2&gt;
        &lt;p&gt;&lt;a href="http://2015fallhw.github.io/2015fallcadpa/category/g2.html"&gt;G2 - Pages&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="http://2015fallhw.github.io/2015fallcadpa/g2_w12_1.html"&gt;G2 - W12  Pages&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://github.com/40323107/2015cadpa_g2/tree/gh-pages"&gt;G2 - Github&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://github.com/40323107/2015cadpa_g2/tree/gh-pages/40323107"&gt;G2 - Github - 40323107&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://www.copy.com/browse/a:dd7adaa;z:copy;b:myfiles"&gt;40323107 - Copy.com&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;		</t>
<t tx="leo.20151201235202.12">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;結論&lt;/h2&gt;
        &lt;p&gt;1.心得&lt;/p&gt;
        &lt;p&gt;2.自評&lt;/p&gt;
        &lt;p&gt;3.啟發&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;心得&lt;/h2&gt;
        &lt;p&gt;&gt; 這一週的課程內容跟上週的內容和任務差不多喔！所以，如果上週進度沒完成的話，就有可能影響到這週的進度。但也不用太擔心啦！還有範例可以參考嘛~~~不然也可以請教會做的人呀！說到這週的任務嘛！一方面是補齊前幾次的作業；一方面則是各組組員互相協調利用 Creo Parametric軟體 來完成 Nutcracker 機構，並繳交團體報告和整理個人作業。反正目前就是運用新的繪圖軟體來完成作業就是了，不過，你也可以嘗試使用之前所學習的繪圖軟體來繪圖啦！我覺得多方面嘗試是很好的行為唷！總之，接下來的進度就是繪製&lt;Nutcracker 機構&gt;的零件與組裝以及各組分工合作完成各週報告。最後，進度層面我還跟得上，而且，如果我有不懂的地方我也會請教同學或教授，所以我才跟得上教學進度。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自評&lt;/h2&gt;
        &lt;p&gt;85 分&lt;/p&gt;
    &lt;/section&gt;    
    &lt;section&gt;
        &lt;h2&gt;啟發&lt;/h2&gt;
        &lt;p&gt;分工合作的重要性&lt;/p&gt;         
    &lt;/section&gt;
&lt;/section&gt;			
				
</t>
<t tx="leo.20151201235202.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151201235202.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151201235202.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151201235202.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151201235202.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151201235202.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151201235202.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;我的報告&lt;/h2&gt;
    &lt;p&gt;第十二週&lt;/p&gt;
    &lt;p&gt;2015 / 12 / 03&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151201235202.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;四設計二甲&lt;/h2&gt;
    &lt;p&gt;40323107&lt;/p&gt;
    &lt;p&gt;廖佑珊&lt;/p&gt;			
&lt;/section&gt;
	
</t>
<t tx="leo.20151201235202.9">&lt;section id="hw-task-one"&gt;
    &lt;h2 align="left"&gt;第十二週筆記&lt;/h2&gt;
    &lt;p align="left"&gt;1.說明課程內容及任務。&lt;/p&gt;
    &lt;p align="left"&gt;2.下載檔案並安裝。&lt;/p&gt;
    &lt;p align="left"&gt;3.利用 `Creo Parametric軟體` 繪製 `Nutcracker 機構`。&lt;/p&gt;
    &lt;p align="left"&gt;4.接續上週的課程內容。&lt;/p&gt;
    &lt;p align="left"&gt;5.觀看課程相關教學影片。&lt;/p&gt;
&lt;/section&gt;


</t>
<t tx="leo.20151201235211.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151201235211.10">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務十三&lt;/h2&gt;
        &lt;p&gt;1.任務說明&lt;/p&gt;
        &lt;p&gt;2.參考網址&lt;/p&gt;
        &lt;p&gt;3.參考影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2 align="left"&gt;任務說明&lt;/h2&gt;
        &lt;p align="left"&gt;(1)修改 fix ，安裝 leo。&lt;/p&gt;
        &lt;p align="left"&gt;(2)閱讀課程內容相關資訊。&lt;/p&gt;
        &lt;p align="left"&gt;(3)利用 Creo Parametric軟體 繪製零件。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考網址&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt; &lt;a href="http://wordpress-2015course.rhcloud.com/?p=4474"&gt;w13&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考影片&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/148455580"&gt;Vimeo - W13 - 1&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/148458668"&gt;Vimeo - W13 - 2&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;

    
   
    
</t>
<t tx="leo.20151201235211.11">&lt;section&gt;
    &lt;section&gt;
        &lt;h1&gt;任務成果&lt;/h1&gt;
        &lt;p&gt;1.機構組裝。&lt;/p&gt;
        &lt;p&gt;2.相關網址。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;機構組裝&lt;/h2&gt;
        &lt;p&gt;(1)機構 3D 等角圖。`(open)`&lt;/p&gt;
        &lt;p&gt;(2)零件 3D 圖。&lt;/p&gt;
        &lt;p&gt;(3)機構組裝影片。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;機構 3D 等角圖`(open)`&lt;/h3&gt;
        &lt;p&gt;&lt;img src="https://copy.com/9fAEhMfx7r2uVvoV"width="450"height="350"&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;機構 3D 等角圖`(close)`&lt;/h3&gt;
        &lt;p&gt;&lt;img src="https://copy.com/KnEwjVgL8wq8MZXa"width="450"height="350"&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;機構組裝影片&lt;/h3&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/152475136"&gt;Nutcracker 機構&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;相關網址&lt;/h2&gt;
        &lt;p&gt;&lt;a href="http://2015fallhw.github.io/2015fallcadpa/category/g2.html"&gt;G2 - Pages&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="http://2015fallhw.github.io/2015fallcadpa/g2_w13_1.html"&gt;G2 - W13  Pages&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://github.com/40323107/2015cadpa_g2/tree/gh-pages"&gt;G2 - Github&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://github.com/40323107/2015cadpa_g2/tree/gh-pages/40323107"&gt;G2 - Github - 40323107&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://www.copy.com/browse/a:dd7adaa;z:copy;b:myfiles"&gt;40323107 - Copy.com&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;	</t>
<t tx="leo.20151201235211.12">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;結論&lt;/h2&gt;
        &lt;p&gt;1.心得&lt;/p&gt;
        &lt;p&gt;2.自評&lt;/p&gt;
        &lt;p&gt;3.啟發&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;心得&lt;/h2&gt;
        &lt;p&gt;這週任務為利用 Creo Parametric軟體 來完成 Nutcracker 機構，並統整出團體報告的資料。你是否有注意到呢？！其實這只是之前進度的延伸而已，已經持續好幾週囉！然而， Creo Parametric軟體 操作方面對於我來說還是覺得有難度，動作都不流暢，好難操作喔！有想放棄的念頭，但事情總是愛跟你唱反調，比如：當你以為快撐不住時，它偏偏就是撐住了，那你還能說什麼呢！總之，我會努力學習的，使我能在操作動作上更流暢，說真的，當你好不容易完成一個零件後，還是會感到很有成就感的。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自評&lt;/h2&gt;
        &lt;p&gt;85 分&lt;/p&gt;
    &lt;/section&gt;    
    &lt;section&gt;
        &lt;h2&gt;啟發&lt;/h2&gt;
        &lt;p&gt;凡事都要努力去嘗試&lt;/p&gt;         
    &lt;/section&gt;
&lt;/section&gt;			
				
</t>
<t tx="leo.20151201235211.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151201235211.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151201235211.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151201235211.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151201235211.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151201235211.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151201235211.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;我的報告&lt;/h2&gt;
    &lt;p&gt;第十三週&lt;/p&gt;
    &lt;p&gt;2015 / 12 / 10&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151201235211.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;四設計二甲&lt;/h2&gt;
    &lt;p&gt;40323107&lt;/p&gt;
    &lt;p&gt;廖佑珊&lt;/p&gt;			
&lt;/section&gt;
	
</t>
<t tx="leo.20151201235211.9">&lt;section id="hw-task-one"&gt;
    &lt;h2 align="left"&gt;第十三週筆記&lt;/h2&gt;
    &lt;p align="left"&gt;1.說明課程內容及任務。&lt;/p&gt;
    &lt;p align="left"&gt;2.下載檔案並安裝。&lt;/p&gt;
    &lt;p align="left"&gt;3.利用 `Creo Parametric軟體` 繪製 `Nutcracker 機構`。&lt;/p&gt;
    &lt;p align="left"&gt;4.觀看課程相關教學影片。&lt;/p&gt;
&lt;/section&gt;

</t>
<t tx="leo.20151201235217.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151201235217.10">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務十四&lt;/h2&gt;
        &lt;p&gt;1.任務說明&lt;/p&gt;
        &lt;p&gt;2.參考網址&lt;/p&gt;
        &lt;p&gt;3.參考影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2 align="left"&gt;任務說明&lt;/h2&gt;
        &lt;p align="left"&gt;(1)閱讀課程內容相關資訊。&lt;/p&gt;
        &lt;p align="left"&gt;(2)利用 Creo Parametric軟體 繪製零件。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考網址&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt; &lt;a href="http://wordpress-2015course.rhcloud.com/?p=4474"&gt;w14&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt; &lt;a href="http://wordpress-2015course.rhcloud.com/?p=4514"&gt;雲端電腦輔助設計繪圖軟體&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考影片&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt; &lt;a href="https://player.vimeo.com/video/148825230"&gt;Vimeo - W14 - 1&lt;/a&gt;&lt;/p&gt;
     &lt;/section&gt;
&lt;/section&gt;

    
</t>
<t tx="leo.20151201235217.11">&lt;section&gt;
    &lt;section&gt;
        &lt;h1&gt;任務成果&lt;/h1&gt;
        &lt;p&gt;1.零件1繪製。&lt;/p&gt;
        &lt;p&gt;2.零件2繪製。&lt;/p&gt;
        &lt;p&gt;3.相關網址。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;零件1繪製&lt;/h2&gt;
        &lt;p&gt;(1)零件 2D 草圖。&lt;/p&gt;
        &lt;p&gt;(2)零件 3D 圖。&lt;/p&gt;
        &lt;p&gt;(3)零件繪製影片。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件 2D 草圖&lt;/h3&gt;
        &lt;p&gt;&lt;img src="https://copy.com/llnwCkBtFl7at2jq"width="450"height="350"&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件 3D 圖&lt;/h3&gt;
        &lt;p&gt;&lt;&lt;script src="https://embed.github.com/view/3d/40323107/2015cadpa_g2/gh-pages/40323107/ADJUSTER_BASE_1-1.stl"&gt;&lt;/script&gt;&lt;/script&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件繪製影片&lt;/h3&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/152472555"&gt;ADJUSTER_BASE-1&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;零件2繪製&lt;/h2&gt;
        &lt;p&gt;(1)零件 2D 草圖。&lt;/p&gt;
        &lt;p&gt;(2)零件 3D 圖。&lt;/p&gt;
        &lt;p&gt;(3)零件繪製影片。&lt;/p&gt;
    &lt;/section&gt;
        &lt;section&gt;
        &lt;h3&gt;零件 2D 草圖&lt;/h3&gt;
        &lt;p&gt;&lt;img src="https://copy.com/dOdpF0u7AEvTSPcs"width="450"height="350"&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件 3D 圖&lt;/h3&gt;
        &lt;p&gt;&lt;script src="https://embed.github.com/view/3d/40323107/2015cadpa_g2/gh-pages/40323107/ADJUSTER_2-2.stl"&gt;&lt;/script&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件繪製影片&lt;/h3&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/152472929"&gt;ADJUSTER-2&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;相關網址&lt;/h2&gt;
        &lt;p&gt;&lt;a href="http://2015fallhw.github.io/2015fallcadpa/category/g2.html"&gt;G2 - Pages&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="http://2015fallhw.github.io/2015fallcadpa/g2_w14_1.html"&gt;G2 - W14  Pages&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://github.com/40323107/2015cadpa_g2/tree/gh-pages/40323107"&gt;G2 - Github - 40323107&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://www.copy.com/browse/a:dd7adaa;z:copy;b:myfiles"&gt;40323107 - Copy.com&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;	</t>
<t tx="leo.20151201235217.12">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;結論&lt;/h2&gt;
        &lt;p&gt;1.心得&lt;/p&gt;
        &lt;p&gt;2.自評&lt;/p&gt;
        &lt;p&gt;3.啟發&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;心得&lt;/h2&gt;
        &lt;p&gt;這週任務一樣是接續上週的進度，內容：各組組員互相協調後，利用 Creo Parametric軟體 來完成 Nutcracker 機構，並彙整資料，完成團體報告及個人作業。經過幾週的摸索後，對於 Creo Parametric軟體 我已經有點熟悉了，操作動作的順暢度也有提升呢！感覺變得比較有趣的說，真奇妙！之前或許是我跟它不熟識的關係，算啦！有趣就行了。後來我領悟到，其實只要你多接觸它、認識它，你就可以從中學到很多，也可以發現它的好處唷！總之，一切還可以，最後我只能說：付出的努力總算是有價值的啦！&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自評&lt;/h2&gt;
        &lt;p&gt;85 分&lt;/p&gt;
    &lt;/section&gt;    
    &lt;section&gt;
        &lt;h2&gt;啟發&lt;/h2&gt;
        &lt;p&gt;凡事都要持之以恆&lt;/p&gt;         
    &lt;/section&gt;
&lt;/section&gt;			
				
</t>
<t tx="leo.20151201235217.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151201235217.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151201235217.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151201235217.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151201235217.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151201235217.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151201235217.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;我的報告&lt;/h2&gt;
    &lt;p&gt;第十四週&lt;/p&gt;
    &lt;p&gt;2015 / 12 / 17&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151201235217.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;四設計二甲&lt;/h2&gt;
    &lt;p&gt;40323107&lt;/p&gt;
    &lt;p&gt;廖佑珊&lt;/p&gt;			
&lt;/section&gt;
	
</t>
<t tx="leo.20151201235217.9">&lt;section id="hw-task-one"&gt;
    &lt;h2 align="left"&gt;第十四週筆記&lt;/h2&gt;
    &lt;p align="left"&gt;1.說明課程內容及任務。&lt;/p&gt;
    &lt;p align="left"&gt;2.修改`fix檔`與安裝`leo檔`。&lt;/p&gt;
    &lt;p align="left"&gt;3.利用 `Creo Parametric軟體` 繪製 `Nutcracker 機構`。&lt;/p&gt;
    &lt;p align="left"&gt;4.觀看課程相關教學影片。&lt;/p&gt;
&lt;/section&gt;


</t>
<t tx="leo.20151201235224.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151201235224.10">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務十五&lt;/h2&gt;
        &lt;p&gt;1.任務說明&lt;/p&gt;
        &lt;p&gt;2.參考網址&lt;/p&gt;
        &lt;p&gt;3.參考影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2 align="left"&gt;任務說明&lt;/h2&gt;
        &lt;p align="left"&gt;(1)閱讀課程內容相關資訊。&lt;/p&gt;
        &lt;p align="left"&gt;(2)利用 Creo Parametric軟體 繪製零件。&lt;/p&gt;
        &lt;p align="left"&gt;(3)於 Onshape軟體 網址創建帳號。&lt;/p&gt;
        &lt;p align="left"&gt;(4)閱讀與熟悉 Onshape軟體 的操作及功能。&lt;/p&gt;
        &lt;p align="left"&gt; (5)利用 `Onshape軟體` 繪製 `Nutcracker 機構`。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考網址&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt; &lt;a href="http://wordpress-2015course.rhcloud.com/?p=4532"&gt;w15&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt; &lt;a href="http://wordpress-2015course.rhcloud.com/?p=4549"&gt;Onshape in Action&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考影片&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt; &lt;a href="https://player.vimeo.com/video/149940498"&gt;Vimeo - W15 - 1&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;


    

    
   
   </t>
<t tx="leo.20151201235224.11">&lt;section&gt;
    &lt;section&gt;
        &lt;h1&gt;任務成果&lt;/h1&gt;
        &lt;p&gt;1.零件3繪製。&lt;/p&gt;
        &lt;p&gt;2.零件4繪製。&lt;/p&gt;
        &lt;p&gt;3.相關網址。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;零件3繪製&lt;/h2&gt;
        &lt;p&gt;(1)零件 2D 草圖。&lt;/p&gt;
        &lt;p&gt;(2)零件 3D 圖。&lt;/p&gt;
        &lt;p&gt;(3)零件繪製影片。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件 2D 草圖&lt;/h3&gt;
        &lt;p&gt;&lt;img src="https://copy.com/WQnQJCqFmruB8sEx"width="450"height="350"&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件 3D 圖&lt;/h3&gt;
        &lt;p&gt;&lt;script src="https://embed.github.com/view/3d/40323107/2015cadpa_g2/gh-pages/40323107/BASE_3-3.stl"&gt;&lt;/script&gt;&lt;/script&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件繪製影片&lt;/h3&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/152475922"&gt;BASE-3&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;零件4繪製&lt;/h2&gt;
        &lt;p&gt;(1)零件 2D 草圖。&lt;/p&gt;
        &lt;p&gt;(2)零件 3D 圖。&lt;/p&gt;
        &lt;p&gt;(3)零件繪製影片。&lt;/p&gt;
    &lt;/section&gt;
        &lt;section&gt;
        &lt;h3&gt;零件 2D 草圖&lt;/h3&gt;
        &lt;p&gt;&lt;img src="https://copy.com/8NLB6nuKXE128ITp"width="450"height="350"&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件 3D 圖&lt;/h3&gt;
        &lt;p&gt;&lt;script src="https://embed.github.com/view/3d/40323107/2015cadpa_g2/gh-pages/40323107/CONNECTION_4-4.stl"&gt;&lt;/script&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件繪製影片&lt;/h3&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/152476284"&gt;CONNECTION-4&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;相關網址&lt;/h2&gt;
        &lt;p&gt;&lt;a href="http://2015fallhw.github.io/2015fallcadpa/category/g2.html"&gt;G2 - Pages&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="http://2015fallhw.github.io/2015fallcadpa/g2_w15_1.html"&gt;G2 - W15  Pages&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://github.com/40323107/2015cadpa_g2/tree/gh-pages"&gt;G2 - Github&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://github.com/40323107/2015cadpa_g2/tree/gh-pages/40323107"&gt;G2 - Github - 40323107&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://www.copy.com/browse/a:dd7adaa;z:copy;b:myfiles"&gt;40323107 - Copy.com&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://cad.onshape.com/documents?filter=recently-opened&amp;column=modifiedAt&amp;order=desc"&gt;40323107 - Onshape軟體&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://cad.onshape.com/documents/a1bdeeceed6141ab8a7607c4/w/cedb5af79e38425d8f8ff16f/e/675b633752c8495cb011974a"&gt;a_g2_nutcracker&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;	</t>
<t tx="leo.20151201235224.12">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;結論&lt;/h2&gt;
        &lt;p&gt;1.心得&lt;/p&gt;
        &lt;p&gt;2.自評&lt;/p&gt;
        &lt;p&gt;3.啟發&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;心得&lt;/h2&gt;
        &lt;p&gt;從這週開始運用新的軟體來繪製 Nutcracker 機構 囉！課程進度會跟上，不過我們組還是會執行自己安排的進度啦！反正就是有辦法兩者兼顧。另外，因為學習到新的知識(軟體)，讓人有種躍躍欲試的情緒呢！因此，廢話不多說、打鐵要趁熱，試吧！然而嘗試後，我覺得比 Creo Parametric軟體 還容易操作，感覺跟 Solid work 軟體 的操作方式很相似，但兩者間還是有差異姓啦！但說真的，簡單很多、容易上手，不過還是有困難的地方，例如：協同的部分讓人想到就頭昏腦脹的，難以理解，幸虧有高手幫忙才得以解脫，不過自己還是得慢慢去理解才行，因為人不能一昧的等待別人來告訴自己答案，而是必須自己去尋求答案，這麼一來學到的才會真的屬於你。總之，從這次的經驗裡，我領悟到很多道理也感覺獲益良多！ &lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自評&lt;/h2&gt;
        &lt;p&gt;85 分&lt;/p&gt;
    &lt;/section&gt;    
    &lt;section&gt;
        &lt;h2&gt;啟發&lt;/h2&gt;
        &lt;p&gt;從學習中獲得經驗&lt;/p&gt;         
    &lt;/section&gt;
&lt;/section&gt;			
				
</t>
<t tx="leo.20151201235224.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151201235224.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151201235224.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151201235224.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151201235224.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151201235224.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151201235224.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;我的報告&lt;/h2&gt;
    &lt;p&gt;第十五週&lt;/p&gt;
    &lt;p&gt;2015 / 12 / 24&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151201235224.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;四設計二甲&lt;/h2&gt;
    &lt;p&gt;40323107&lt;/p&gt;
    &lt;p&gt;廖佑珊&lt;/p&gt;			
&lt;/section&gt;
	
</t>
<t tx="leo.20151201235224.9">&lt;section id="hw-task-one"&gt;
    &lt;h2 align="left"&gt;第十五週筆記&lt;/h2&gt;
    &lt;p align="left"&gt;1.說明課程內容及任務。&lt;/p&gt;
    &lt;p align="left"&gt;2.利用 `Creo Parametric軟體` 繪製 `Nutcracker 機構`。&lt;/p&gt;
    &lt;p align="left"&gt;3.於`Onshape軟體`網址創建帳號。&lt;/p&gt;
    &lt;p align="left"&gt;4.說明`Onshape軟體`的操作及功能。&lt;/p&gt;
    &lt;p align="left"&gt;5.利用 `Onshape軟體` 繪製 `Nutcracker 機構`。&lt;/p&gt;
&lt;/section&gt;


</t>
<t tx="leo.20151201235230.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151201235230.10">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務十六&lt;/h2&gt;
        &lt;p&gt;1.任務說明&lt;/p&gt;
        &lt;p&gt;2.參考網址&lt;/p&gt;
        &lt;p&gt;3.參考影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2 align="left"&gt;任務說明&lt;/h2&gt;
        &lt;p align="left"&gt;(1)閱讀課程相關文章。&lt;/p&gt;
        &lt;p align="left"&gt;(2)利用 `Onshape軟體 `繪製零件。&lt;/p&gt;
        &lt;p align="left"&gt;(3)觀看課程教學影片。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考網址&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt; &lt;a href="http://wordpress-2015course.rhcloud.com/?p=4584"&gt;w16&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考影片&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt; &lt;a href="https://player.vimeo.com/video/150401255"&gt;Vimeo - W16 - 1&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/150140635"&gt;Vimeo - W16 - 2&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;

    

    

</t>
<t tx="leo.20151201235230.12">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;結論&lt;/h2&gt;
        &lt;p&gt;1.心得&lt;/p&gt;
        &lt;p&gt;2.自評&lt;/p&gt;
        &lt;p&gt;3.啟發&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;心得&lt;/h2&gt;
        &lt;p&gt;時間過得好快唷！轉瞬間就已經接近學期的尾聲了，顯然又到了最關鍵的時段啦！好多資料要統整的說。廢話不多說，馬上切入本週的主題吧！到了這時候你應該也有所發現，從W10 ~W16，我們好像都在處理同一件事情呢！只是偶而會增加一些難度，但也還好，不致於應付不來，總之，其實課程是一直堆疊上來的，所以每個環節都很重要呢！因此，到了這週，是在提醒我是該準備統整資料囉！不然就會來不及了，有點像趕快把燙手芋泥賣掉,，不然就要倒大楣了，又像是在諷刺說：平時不準備，事到臨頭才著急，可惜已經太晚啦！咎由自取。扯太遠了，這週的任務是尋找方法計算出 Nutcracker 機構 的有效運動距離，方法不限，總之，就是不管你運用何種方式，只要能求得答案行了。換句話說，雖然結果只有一個，但解決辦法確有很多種，只是看你想不想的到、用不用的到而已。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自評&lt;/h2&gt;
        &lt;p&gt;85 分&lt;/p&gt;
    &lt;/section&gt;    
    &lt;section&gt;
        &lt;h2&gt;啟發&lt;/h2&gt;
        &lt;p&gt;很多事物都有異曲同工之處&lt;/p&gt;         
    &lt;/section&gt;
&lt;/section&gt;			
				
</t>
<t tx="leo.20151201235230.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151201235230.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151201235230.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151201235230.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151201235230.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151201235230.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151201235230.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;我的報告&lt;/h2&gt;
    &lt;p&gt;第十六週&lt;/p&gt;
    &lt;p&gt;2015 / 12 / 31&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151201235230.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;四設計二甲&lt;/h2&gt;
    &lt;p&gt;40323107&lt;/p&gt;
    &lt;p&gt;廖佑珊&lt;/p&gt;			
&lt;/section&gt;
	
</t>
<t tx="leo.20151201235230.9">&lt;section id="hw-task-one"&gt;
    &lt;h2 align="left"&gt;第十六週筆記&lt;/h2&gt;
    &lt;p align="left"&gt;1.說明課程內容及任務。&lt;/p&gt;
    &lt;p align="left"&gt;2.利用 `Onshape軟體`繪製零件。&lt;/p&gt;
    &lt;p align="left"&gt;3.說明如何計算`Nutcracker 機構`的有效運動距離。&lt;/p&gt;
    &lt;p align="left"&gt;4.觀看課程相關教學影片。&lt;/p&gt;
&lt;/section&gt;


</t>
<t tx="leo.20151201235237.1">@language xml
@tabwidth -4
@others

</t>
<t tx="leo.20151201235237.10">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;任務十七&lt;/h2&gt;
        &lt;p&gt;1.任務說明&lt;/p&gt;
        &lt;p&gt;2.參考網址&lt;/p&gt;
        &lt;p&gt;3.參考影片&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2 align="left"&gt;任務說明&lt;/h2&gt;
        &lt;p align="left"&gt;(1)自我評分。&lt;/p&gt;
        &lt;p align="left"&gt;(2)閱讀課程相關文章。&lt;/p&gt;
        &lt;p align="left"&gt;(3)計算 Nutcracker 機構 的有效運動距離。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考網址&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt; &lt;a href="http://wordpress-2015course.rhcloud.com/?p=4610"&gt;w17&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;參考影片&lt;/h2&gt;
        &lt;p&gt;請參考&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/150985277"&gt;Vimeo - W17 - 1&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://player.vimeo.com/video/150636968"&gt;Vimeo - W17 - 2&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;

</t>
<t tx="leo.20151201235237.11">&lt;section&gt;
    &lt;section&gt;
        &lt;h1&gt;任務成果&lt;/h1&gt;
        &lt;p&gt;1.相關圖片。&lt;/p&gt;
        &lt;p&gt;2.相關網址。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;相關圖片&lt;/h2&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;p&gt;&lt;img src="https://copy.com/SlU4fBfIT9IhbAyl"width="450"height="350"&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;p&gt;&lt;img src="https://copy.com/OFpgK043fiogZjSW"width="450"height="350"&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;p&gt;&lt;img src="https://copy.com/rHrxpJW0jsiQBKQv"width="450"height="350"&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;        
        &lt;p&gt;&lt;img src="https://copy.com/u4ZnKqfUoWbvFoJo"width="450"height="350"&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;相關網址&lt;/h2&gt;
        &lt;p&gt;&lt;a href="http://2015fallhw.github.io/2015fallcadpa/category/g2.html"&gt;G2 - Pages&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="http://2015fallhw.github.io/2015fallcadpa/g2_w17_1.html"&gt;G2 - W17  Pages&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://www.copy.com/browse/a:dd7adaa;z:copy;b:myfiles"&gt;40323107 - Copy.com&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;		






</t>
<t tx="leo.20151201235237.12">&lt;section&gt;
    &lt;section&gt;
        &lt;h2&gt;結論&lt;/h2&gt;
        &lt;p&gt;1.心得&lt;/p&gt;
        &lt;p&gt;2.自評&lt;/p&gt;
        &lt;p&gt;3.啟發&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;心得&lt;/h2&gt;
        &lt;p&gt;本週的主要任務是各週資料統整還有期末自評唷！ 一轉眼，學期末就到啦！感覺一切好不真實，回想前幾週的點滴，總覺得像過眼雲煙那般，看似忙碌又好像不忙碌，好像有種反複做著相同動作的錯覺呢！回想這幾週所學習到的知識，很多，一下子腦袋瓜有點負荷不了，但還是有喘息的空間啦！總之，若要我做個各週資料統整的話，感覺非難非易，因為人的記憶是有限的，有時它會自動過濾並刪除一些資訊，所以才需要科技的幫忙呢！也就是說，透過筆記、詢問、影片觀賞...等，真的能幫助我找回失落的記憶呢！還有，透過這次的體驗，從中我也領悟到很多道理呢！好比說：獨樂樂不如眾樂樂還有別把事情想得太複雜，其實它的道理很簡單的，也就是說：我們不能將事情由簡化難，而是要做到化難為簡，這個道理看似很簡單，做起來卻很難呢！另外，關於分組協同的部分，有很多地方還要再磨練磨練才行，雖然想做好，但要設想的層面太廣了，不過這真的是一個很難得的經驗，總之，在這門課程裡我真的學到很多，很難用言語來形容的感覺，所以也只能說：獲益良多。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h2&gt;自評&lt;/h2&gt;
        &lt;p&gt;85 分&lt;/p&gt;
    &lt;/section&gt;    
    &lt;section&gt;
        &lt;h2&gt;啟發&lt;/h2&gt;
        &lt;p&gt;知識是源源不絕的&lt;/p&gt;         
    &lt;/section&gt;
&lt;/section&gt;			
				
</t>
<t tx="leo.20151201235237.13">&lt;script src="lib/js/head.min.js"&gt;&lt;/script&gt;
&lt;script src="js/reveal.min.js"&gt;&lt;/script&gt;
&lt;script&gt;
    // 啟動 Reveal.
    Reveal.initialize({
    });
&lt;/script&gt;
	
</t>
<t tx="leo.20151201235237.2">&lt;!--
這個檔案展示了 reveal.js 投影片資料的基本架構
其中使用 "reveal" class 與 "slides" class 來界定投影片的資料範圍
而各投影片則以 &lt;section&gt;&lt;/section&gt; 標示
且支援平行與垂直的投影片配置方法
--&gt;
</t>
<t tx="leo.20151201235237.3">&lt;!doctype html&gt;
&lt;html lang="en"&gt;
&lt;head&gt;
&lt;meta charset="utf-8"&gt;
&lt;title&gt;最簡單的 reveal 超文件&lt;/title&gt;
&lt;link rel="stylesheet" href="css/reveal.min.css"&gt;
	&lt;link rel="stylesheet" href="css/theme/default.css" id="theme"&gt;	
	&lt;!--增加對於 IE 早期版本的支援 --&gt;
	&lt;!--[if lt IE 9]&gt;
	&lt;script src="lib/js/html5shiv.js"&gt;&lt;/script&gt;
	&lt;![endif]--&gt;
&lt;/head&gt;
@others
</t>
<t tx="leo.20151201235237.4">&lt;body&gt;
@others
&lt;/body&gt;
</t>
<t tx="leo.20151201235237.5">&lt;!-- 將整個投影片包在 "reveal" class 中 --&gt;
&lt;div class="reveal"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151201235237.6">&lt;!-- 將所有投影片包在 "slides" class 中 --&gt;
&lt;div class="slides"&gt;
@others
&lt;/div&gt;
</t>
<t tx="leo.20151201235237.7">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;我的報告&lt;/h2&gt;
    &lt;p&gt;第十七週&lt;/p&gt;
    &lt;p&gt;2016 / 01 / 07&lt;/p&gt;		
&lt;/section&gt;
	
</t>
<t tx="leo.20151201235237.8">&lt;!-- 以下為投影片 --&gt;
&lt;!-- 每一個 section 都代表一張投影片,  --&gt;
&lt;!-- section 標註中的多 section 標註, 將往下垂直延伸 --&gt;
&lt;section&gt;
    &lt;h2&gt;四設計二甲&lt;/h2&gt;
    &lt;p&gt;40323107&lt;/p&gt;
    &lt;p&gt;廖佑珊&lt;/p&gt;			
&lt;/section&gt;
	
</t>
<t tx="leo.20151201235237.9">&lt;section id="hw-task-one"&gt;
    &lt;h2 align="left"&gt;第十七週筆記&lt;/h2&gt;
    &lt;p align="left"&gt;1.說明課程內容及任務。&lt;/p&gt;
    &lt;p align="left"&gt;2.自我評分。&lt;/p&gt;
    &lt;p align="left"&gt;3.利用 `Onshape軟體`繪製零件。&lt;/p&gt;
    &lt;p align="left"&gt;4.說明如何計算`Nutcracker 機構`的有效運動距離。&lt;/p&gt;
    &lt;p align="left"&gt;5.說明評分時程規劃。&lt;/p&gt;
    &lt;p align="left"&gt;6.看課程相關教學影片。&lt;/p&gt;
&lt;/section&gt;



</t>
<t tx="leo.20160121164943.1">&lt;section&gt;
    &lt;section&gt;
        &lt;h1&gt;任務成果&lt;/h1&gt;
        &lt;p&gt;1.零件繪製。&lt;/p&gt;
        &lt;p&gt;2.零件組合。&lt;/p&gt;
        &lt;p&gt;3.相關網址。&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;   
&lt;section&gt;     
    &lt;section&gt;
        &lt;h2&gt;零件7繪製&lt;/h2&gt;
        &lt;p&gt;(1)零件七  2D 草圖。&lt;/p&gt;
        &lt;p&gt;(2)零件七 繪製流程。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件七 2D 草圖&lt;/h3&gt;
        &lt;p&gt;&lt;img src="https://copy.com/BfjeElFXaQRe97gn"width="450"height="350"&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件七 繪製流程。&lt;/h3&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h4&gt;(1)繪製草圖1：以`上視圖`(Top)做基準面，繪製一個`U型圖`，依據`2D草圖`所給予的尺寸來標註。&lt;/h4&gt;
        &lt;p&gt;&lt;img src="https://copy.com/Eo6gZnyaLQuYB0F7"&gt;&lt;/img&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h4&gt;(2)伸長填料`(擠出1)`：以`上視圖`(Top)為基準，兩側對稱向`左右`伸長 0.75in。&lt;/h4&gt;
        &lt;p&gt;&lt;img src="https://copy.com/YaTpf9ASUaWVIIsG"&gt;&lt;/img&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h4&gt;(3)繪製草圖2：以`右視圖`(Right)向後，物體平行右視圖最遠的面`(面1)`做基準面，繪製一個`直徑 0.25 的圓`。&lt;/h4&gt;
        &lt;p&gt;&lt;img src="https://copy.com/pMhgXxhMseCRMZrZ"&gt;&lt;/img&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h4&gt;(4)伸長除料`(擠出2)`：以`面1`做基底，向`前`完全貫穿物體除料。&lt;/h4&gt;
        &lt;p&gt;&lt;img src="https://copy.com/hcGFD1GRDTqHWvJw"&gt;&lt;/img&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h4&gt;(5)繪製草圖3：以物體底座`(面2)`做基準面，繪製兩個`直徑 0.25 的圓`且互相對稱，圓心距離`上邊`為 0.25in、距離`兩側`各為 0.2in。&lt;/h4&gt;
        &lt;p&gt;&lt;img src="https://copy.com/HqlLGZieIaqGxOut"&gt;&lt;/img&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h4&gt;(6)伸長除料`(擠出3)`：以`面2`做基底，向`後`(右)刪除 0.5in。&lt;/h4&gt;
        &lt;p&gt;&lt;img src="https://copy.com/JmsqOCm3nTUC6TPG"&gt;&lt;/img&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h4&gt;(7)零件完成。&lt;/h4&gt;
        &lt;p&gt;&lt;img src="https://copy.com/Cq6b4PUpdRe8K6AL"&gt;&lt;/img&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;   
&lt;section&gt;      
    &lt;section&gt;
        &lt;h2&gt;零件8繪製&lt;/h2&gt;
        &lt;p&gt;(1)零件八 2D 草圖。&lt;/p&gt;
        &lt;p&gt;(2)零件八 繪製流程。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件八  2D 草圖&lt;/h3&gt;
        &lt;p&gt;&lt;img src="https://copy.com/ngfUdrXkskTKIfZD"width="450"height="350"&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件八 繪製流程&lt;/h3&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h4&gt;(1)繪製草圖1：以`前視圖`(Front)做基準面，繪製一個`直徑 0.995 的圓`。&lt;/h4&gt;
        &lt;p&gt;&lt;img src="https://copy.com/E0GYdrZlMDSJAFbv"&gt;&lt;/img&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h4&gt;(2)伸長填料`(擠出1)`：以`前視圖`(Front)做基底，向`前`伸長 5in。&lt;/h4&gt;
        &lt;p&gt;&lt;img src="https://copy.com/yA9JubVuMyHHh10V"&gt;&lt;/img&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h4&gt;(3)繪製草圖2：以`物體向前伸長的那一面`(面1)`做基準面，繪製兩個矩形，並互相對稱，矩形靠近圓心的那一邊與圓心距離為 0.25in。&lt;/h4&gt;
        &lt;p&gt;&lt;img src="https://copy.com/j2CqaBI3eHIuduqh"&gt;&lt;/img&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h4&gt;(4)伸長除料`(擠出2)`：以`面1`做基底，向`後`刪除 1in。&lt;/h4&gt;
        &lt;p&gt;&lt;img src="https://copy.com/ts1WVnZeSWzhFNvF"&gt;&lt;/img&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h4&gt;(5)繪製草圖3：以`除料後`的某一面`(面2)`做基準面，繪製一個`直徑 0.25 的圓`且圓心距離面1為 0.25in。&lt;/h4&gt;
        &lt;p&gt;&lt;img src="https://copy.com/V9QN9EmJja7g9w1F"&gt;&lt;/img&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h4&gt;(6)伸長除料`(擠出3)`：以`面2`做基底，向`前`(右)刪除 1in。&lt;/h4&gt;
        &lt;p&gt;&lt;img src="https://copy.com/t6NQBHNaXvdaXeq1"&gt;&lt;/img&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h4&gt;(7)繪製草圖4：以`右視圖`(Right)做基準面，繪製兩條線相互垂直及一個`直徑 1`的半圓，且垂直線距離原點(前視圖的中心點)為 0.25in。&lt;/h4&gt;
        &lt;p&gt;&lt;img src="https://copy.com/uGnpoGxTvRaRQQlG"&gt;&lt;/img&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h4&gt;(8)旋轉除料`(擠出4)`：以`距離原點(前視圖的中心點)為 0.25in的垂直線`做軸心，`逆`時針旋轉除料。&lt;/h4&gt;
        &lt;p&gt;&lt;img src="https://copy.com/0xZhDobFLy1Uxj8H"&gt;&lt;/img&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h4&gt;(9)零件完成。&lt;/h4&gt;
        &lt;p&gt;&lt;img src="https://copy.com/vIAtGH8KgBWLljHv"&gt;&lt;/img&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;   
&lt;section&gt;      
    &lt;section&gt;
        &lt;h2&gt;零件組合&lt;/h2&gt;
        &lt;p&gt;(1)零件 3D 草圖。&lt;/p&gt;
        &lt;p&gt;(2)零件組裝圖。&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件 3D 草圖&lt;/h3&gt;
        &lt;p&gt;&lt;img src="https://copy.com/Aq9DM4uTOgW0tJOw"width="450"height="350"&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h3&gt;零件組裝圖&lt;/h3&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h4&gt;(1)a_g2_nutcracker - 40323107- Nutcracker 機構(close)&lt;/h4&gt;
        &lt;p&gt;&lt;img src="https://copy.com/nUtDHndz6k8FKRF1"&gt;&lt;/img&gt;&lt;/p&gt;
    &lt;/section&gt;
    &lt;section&gt;
        &lt;h4&gt;(2)a_g2_nutcracker - 40323107- Nutcracker 機構(open)&lt;/h4&gt;
        &lt;p&gt;&lt;img src="https://copy.com/2DfCCXbxYcawNHp1"&gt;&lt;/img&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;   
&lt;section&gt;      
    &lt;section&gt;
        &lt;h2&gt;相關網址&lt;/h2&gt;
        &lt;p&gt;&lt;a href="http://2015fallhw.github.io/2015fallcadpa/category/g2.html"&gt;G2 - Pages&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="http://2015fallhw.github.io/2015fallcadpa/g2_w16_1.html"&gt;G2 - W16  Pages&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://www.copy.com/browse/a:dd7adaa;z:copy;b:myfiles"&gt;40323107 - Copy.com&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://cad.onshape.com/documents?filter=recently-opened&amp;column=modifiedAt&amp;order=desc"&gt;40323107 - Onshape軟體&lt;/a&gt;&lt;/p&gt;
        &lt;p&gt;&lt;a href="https://cad.onshape.com/documents/a1bdeeceed6141ab8a7607c4/w/cedb5af79e38425d8f8ff16f/e/675b633752c8495cb011974a"&gt;a_g2_nutcracker&lt;/a&gt;&lt;/p&gt;
    &lt;/section&gt;
&lt;/section&gt;   
    


     

       
 

	</t>
</tnodes>
</leo_file>
